//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by flyExplorer.rc
//
#define IDC_PROPERTIES                  3
#define IDC_ABOUT_BUG                   3
#define IDC_GO_PATH_EXP2_PATH           3
#define IDC_PIC_CONV_COLOR_APPLY_ALL    3
#define IDC_SHARED_PROC_PROPERTIES      3
#define IDC_CFG_APPLY                   3
#define IDC_GO_PATH_EXP1_PATH           4
#define IDC_CFG_DEFAULT                 4
#define IDC_SEARCH_SYSTEM               5
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUT                       100
#define IDS_CLIPBOARD_METAFILE_FORMAT   101
#define IDD_CFG_GENERAL                 103
#define IDD_CFG_CONTENTS                105
#define IDD_CFG_EXP                     106
#define IDR_MAINFRAME                   128
#define IDB_TB_MAIN_HOT                 130
#define IDB_TB_MAIN_HOT_LARGE           130
#define IDB_TB_MAIN_COLD                131
#define IDB_TB_MAIN_COLD_LARGE          131
#define IDR_CONTEXT_MENU                132
#define IDB_ABOUT                       133
#define IDD_SHORTCUT                    134
#define IDD_CREATE_SHORTCUT             134
#define IDB_SHORTCUT                    135
#define IDD_RENAME                      137
#define IDB_CONTENTS                    145
#define IDR_SEARCH_RESULT               164
#define IDD_CFG_MGR                     175
#define IDI_TRAY                        181
#define IDD_CFG_ADV                     190
#define IDD_FILE_SCRAP                  206
#define IDB_OPTIONS_PANEL_IMAGES        218
#define IDD_CFG_EXP_THUMB               222
#define IDD_CONTENTS                    223
#define IDD_LINK_EDIT                   223
#define IDD_BOOKMARK_ITEM_EDIT          223
#define IDD_TEXTOUT                     226
#define IDD_FILE_LIST                   226
#define IDD_DRIVE_INFO                  233
#define IDD_DRIVE_DETAIL                234
#define IDI_SHORTCUT                    235
#define IDI_TIP                         236
#define IDD_PIC_VIEWER                  237
#define IDD_TIP                         239
#define IDD_LINK                        261
#define IDD_BOOKMARK_EDIT               261
#define IDD_RENAME_TIP                  264
#define IDI_TRAY_XP                     265
#define IDD_PRINT_PREVIEW               271
#define IDB_PREVIEW_ZOOMIN_COLD         274
#define IDB_PREVIEW_NEXT_HOT            275
#define IDB_PREVIEW_PREV_COLD           276
#define IDB_PREVIEW_PREV_HOT            277
#define IDB_PREVIEW_PRINT_COLD          278
#define IDB_PREVIEW_PRINT_HOT           279
#define IDB_PREVIEW_NEXT_COLD           280
#define IDB_PREVIEW_ZOOMIN_HOT          281
#define IDB_PREVIEW_ZOOMOUT_COLD        282
#define IDB_PREVIEW_ZOOMOUT_HOT         283
#define IDD_SEARCH                      287
#define IDD_SEL_NAME                    288
#define IDD_PIC_CONV                    290
#define IDD_PIC_CONV_OPTION             291
#define IDD_PIC_CONV_COLOR              293
#define IDB_SEARCH                      297
#define IDD_TEXT_JOIN                   306
#define IDD_TEXT_MERGE                  306
#define IDD_FILE_SCRAP_DROP             307
#define IDB_FILE_SCRAP_DROP             308
#define IDI_LINK                        310
#define IDD_NEW_ITEMS                   312
#define IDD_NEW_BATCH_ITEM              312
#define IDD_BATCH_CREATE                312
#define IDD_WHO_USES                    315
#define IDD_SHARED_PROC                 315
#define IDD_DOS_CMD                     317
#define IDI_DOS_CMD                     318
#define IDD_FOLDER_CUSTOM               319
#define IDD_SEL_ICON                    320
#define IDB_TB_MAIN_HOT_SMALL           321
#define IDB_TB_MAIN_COLD_SMALL          323
#define IDD_CUSTOM_TOOLBAR              324
#define IDD_DRIVE                       326
#define IDB_TB_DRIVEDLG                 327
#define IDD_ACCELERATOR                 328
#define IDD_ACCEL                       328
#define IDI_GO_UP                       333
#define IDD_CRC                         334
#define IDD_CRC_CREATE                  334
#define IDD_CRC_CHECK                   336
#define IDD_CRC_VERIFY                  336
#define IDD_CFG_STYLE                   339
#define IDB_CONFIG_TREE                 340
#define IDD_INPUT                       342
#define IDD_CFG_EXP_FILTER              346
#define IDD_EXT_FILTER                  347
#define IDD_EXT_FLT                     347
#define IDD_FILTER                      347
#define IDD_FILTER_SET                  347
#define IDD_CFG_EXP_VIEWSET             348
#define IDD_FILE_SCRAP_GROUP            349
#define IDI_NOT                         350
#define IDR_EXP_STYLE_MENU              351
#define IDR_EXP_VIEW_STYLE              351
#define IDR_EXP_FILESYSTEM_POPUP        352
#define IDR_EXP_NONFILESYSTEM_POPUP     353
#define IDR_GO_BACK                     354
#define IDR_GO_FORWARD                  355
#define IDR_COOLBAR_MENUBAR             356
#define IDR_TRAY                        357
#define IDR_VIEW_SPLIT                  359
#define IDR_SPLIT_VIEW                  359
#define IDR_EXP_COLUMN                  361
#define IDR_PIC_VIEWER                  362
#define IDR_GO_BOOKMARK                 364
#define IDR_FILE_SCRAP_DROP             365
#define IDR_RENAME_FORMAT               366
#define IDR_GO_UP                       367
#define IDR_NEW_ITEMS                   368
#define IDR_COOLBAR_TOOLBAR             369
#define IDR_COOLBAR_DRIVEBAR            370
#define IDR_COOLBAR_BOOKMARKBAR         371
#define IDR_GO_DRIVE                    372
#define IDD_RENAME_EDIT                 373
#define IDD_ATTRIBUTE                   374
#define IDD_CFG_EXP_DISP                375
#define IDD_CFG_FUNC                    376
#define IDR_DRIVE_PATHBAR               377
#define IDD_CFG_DISP                    377
#define IDD_CFG_EXP_WND1                378
#define IDD_CFG_EXP_WND                 378
#define IDD_CFG_FUNC_REFRESH            380
#define IDD_CFG_FUNC_SPLIT              381
#define IDD_CFG_FUNC_FILE_SCRAP         382
#define IDD_CFG_FUNC_DRAG               383
#define IDD_GO_PATH                     386
#define IDD_RENAME_1                    388
#define IDD_RENAME_2                    389
#define IDD_RENAME_3                    390
#define IDD_RENAME_4                    391
#define IDD_RENAME_5                    392
#define IDB_TB_RENAME                   394
#define IDD_PARAM_EXEC                  395
#define IDD_SYNC_DIRS                   396
#define IDR_SPLITTER                    397
#define IDD_NEW_ITEM                    398
#define IDD_CREATE_ITEM                 398
#define IDD_CFG_FUNC_LINK               399
#define IDD_CFG_FUNC_BOOKMARK           399
#define IDD_CFG_FOLDER                  400
#define IDD_CFG_FLD                     400
#define IDR_GO_HISTORY                  401
#define IDD_CFG_FUNC_RENAME             401
#define IDD_COMPARE                     402
#define IDR_SEARCH_LOC                  402
#define IDD_SYNC                        402
#define IDD_FOLDER_SYNC                 402
#define IDR_SYNC                        403
#define IDD_SEARCH_LOC                  403
#define IDD_HISTORY                     404
#define IDR_FILE_SCRAP                  404
#define IDI_SEARCH                      405
#define IDD_SEARCH_LOC_EDIT             405
#define IDD_SYNC_OPTION                 406
#define IDD_FOLDER_SYNC_OPTION          406
#define IDI_SEARCH_EXC                  407
#define IDD_WAIT                        407
#define IDI_SEARCH_INC                  408
#define IDD_FILE_SPLIT                  408
#define IDI_EXPAND                      409
#define IDD_FILE_COMBINE                409
#define IDB_SYNC_IMAGE_LIST             410
#define IDD_FILE_MERGE                  410
#define IDB_SYNC_IMAGES                 411
#define IDD_CFG_FUNC_FILEASS            411
#define IDD_CFG_FUNC_FILE_ASS           411
#define IDD_FILE_ASS_SET                412
#define IDD_FILE_ASS                    413
#define IDD_SEL_FILTER                  414
#define IDD_COLUMN_SET                  415
#define IDI_FILE_SCRAP                  415
#define IDD_CFG_DISP_SIZE               416
#define IDR_FILE_VIEW                   416
#define IDD_SIZE_UNIT                   417
#define IDD_SIZE_FORMAT                 417
#define IDR_FILE_EDIT                   417
#define IDD_CFG_ADV_PATH                418
#define IDD_SEL_FOLDER                  419
#define IDI_PENDING                     420
#define IDD_CFG_FLD_WND                 421
#define IDD_BATCH_CREATE_FMT            422
#define IDR_MENU1                       422
#define IDR_GO_WORKING_FOLDER           422
#define IDD_BATCH_CREATE_TEXT           423
#define IDR_TAB                         423
#define IDD_CFG_ADV_HOTKEY              424
#define IDD_CFG_ADV_PATH1               424
#define IDD_CFG_FUNC_HISTORY            425
#define IDD_CFG_FUNC_FILEOP             426
#define IDD_CFG_FUNC_FILE_OP            426
#define IDC_ABOUT_WINDOWS               1000
#define IDC_ABOUT_NAME                  1001
#define IDC_CREATE_SHORTCUT_STARTUP     1002
#define IDC_SEARCH_TEXT                 1002
#define IDC_SHORTCUT_TARGET             1003
#define IDC_CREATE_SHORTCUT_TARGET      1003
#define IDC_BROWSE                      1005
#define IDC_SHORTCUT_BROWSE             1005
#define IDC_BATCH_RENAME_FORMAT_NUMBER  1007
#define IDC_BATCH_RENAME_FORMAT_INCREASE 1008
#define IDC_BATCH_RENAME_FORMAT_NUMBER_SPIN 1009
#define IDC_BATCH_RENAME_FORMAT_INCREASE_SPIN 1010
#define IDC_BATCH_RENAME_FORMAT         1011
#define IDC_BATCH_RENAME_LISTCTRL       1012
#define IDC_BATCH_RENAME_FORMAT_LENGTH  1012
#define IDC_BATCH_RENAME_FORMAT_LENGTH_SPIN 1013
#define IDC_BATCH_RENAME_REPLACE_APPLY  1013
#define IDC_BATCH_RENAME_REPLACE_OLD    1014
#define IDC_BATCH_RENAME_REPLACE_NEW    1015
#define IDC_BATCH_RENAME_INIT           1016
#define IDC_BATCH_RENAME_INSERT_POS     1017
#define IDC_BATCH_RENAME_INSERT_POS_SPIN 1018
#define IDC_BATCH_RENAME_FORMAT_APPLY   1019
#define IDC_BATCH_RENAME_INSERT_APPLY   1020
#define IDC_BATCH_RENAME_INSERT         1021
#define IDC_BATCH_RENAME_INSERT_STRING  1021
#define IDC_BATCH_RENAME_ON_RESULT      1022
#define IDC_BATCH_RENAME_FORMAT_DESC    1023
#define IDC_CFG_CONTENTS_NONE           1023
#define IDC_BATCH_RENAME_DELETE_POS     1024
#define IDC_CFG_CONTENTS_STANDARD       1024
#define IDC_BATCH_RENAME_DELETE_POS_SPIN 1025
#define IDC_CFG_CONTENTS_BASIC          1025
#define IDC_BATCH_RENAME_BATCH_FORMAT_APPLY 1026
#define IDC_CFG_GENERAL_DOUBLE_CLICK    1026
#define IDC_BATCH_RENAME_DELETE_APPLY   1027
#define IDC_CFG_EXP_VIEW_SAME_BETWEEN_SPLIT 1027
#define IDC_BATCH_RENAME_DELETE_LENGTH  1028
#define IDC_CFG_EXP_VIEW_EACH_FOLDER    1028
#define IDC_CFG_FUNC_RENAME_EXT_SEL_EXCEPT_FOR_EXT 1028
#define IDC_CRC_EACH                    1029
#define IDC_LINK                        1029
#define IDC_GRIDLINES                   1029
#define IDC_CLOSE                       1029
#define IDC_DEFAULT1                    1029
#define IDC_SAVE_CHACHE                 1029
#define IDC_TIP_STARTUP                 1029
#define IDC_OPEN                        1029
#define IDC_UL                          1029
#define IDC_SPIN_SPEC_DELETE_LENGTH     1029
#define IDC_SUBFOLDER                   1029
#define IDC_INTERLACED                  1029
#define IDC_TIP_NO_STARTUP              1029
#define IDC_CRCCREATE_EACH              1029
#define IDC_PIC_CONV_KEEP_ORG           1029
#define IDC_PIC_CONV_COLOR_RADIO_GRAYSCALE 1029
#define IDC_PIC_CONV_OPTION_CHECK_INTERLACED 1029
#define IDC_BATCH_RENAME_DELETE_LENGTH_SPIN 1029
#define IDC_SEARCH_SUBFOLDER            1029
#define IDC_CFG_CONTENTS_BOOKMARK       1029
#define IDC_CFG_EXP_THUMB_CACHE         1029
#define IDC_CFG_STYLE_SINGLE_FOLDER_PANE 1029
#define IDC_CFG_EXP_WND_INIT_FOLDER     1029
#define IDC_CFG_FUNC_RENAME_SINGLE_RENAME_BY_BATCH_RENAME 1029
#define IDC_BATCH_RENAME_EDIT           1030
#define IDC_DOS_NO_CLOSE                1030
#define IDC_FILE_LIST_BY_LINE           1030
#define IDC_SEARCH_CASE                 1030
#define IDC_FOLDER_SYNC_COMPARE         1030
#define IDC_CFG_CONTENTS_NO_DISP_INFO   1030
#define IDC_CFG_EXP_THUMB_LOAD_BY_EXT   1030
#define IDC_CFG_GENERAL_SHOW_HIDDEN_FILE 1030
#define IDC_CFG_STYLE_COMMANDER         1030
#define IDC_CFG_EXP_WND_INIT_LAST_FOLDER 1030
#define IDC_CFG_FUNC_BOOKMARK_SHOW_TOOLTIP 1030
#define IDC_FILE_LIST_ONLY_FILE         1031
#define IDC_PIC_CONV_OPTION_CHECK_PALLETE_TRANSPARENT 1031
#define IDC_BATCH_RENAME_ITEM_EDIT      1031
#define IDC_BATCH_RENAME_REPLACE_REPEAT 1031
#define IDC_SEARCH_NO_WILDCARD          1031
#define IDC_CFG_GENERAL_TITLE_FULL_PATH 1031
#define IDC_CFG_EXP_WND_INIT_FOLDER_NONE 1031
#define IDC_CFG_FUNC_BOOKMARK_FAST_NET_ICON 1031
#define IDC_FILE_LIST_WITH_EXT          1032
#define IDC_PIC_CONV_OPTION_CHECK_PROGRESSIVE 1032
#define IDC_BATCH_RENAME_REPLACE_REPEAT_SPIN 1032
#define IDC_CFG_ADV_PATH_CUSTOM         1032
#define IDC_CFG_EXP_UP_AND_SEL_ITEM     1032
#define IDC_CFG_GENERAL_ADDRESS_BAR_FULL_PATH 1032
#define IDC_FILE_LIST_WITH_INFO         1033
#define IDC_PIC_CONV_OPTION_CHECK_LOSSLESS 1033
#define IDC_BATCH_RENAME_CASE_APPLY     1033
#define IDC_CFG_ADV_PATH_EACH_CUSTOM    1033
#define IDC_CFG_GENERAL_SHOW_TOOLTIP    1033
#define IDC_EXT_COLOR_INPUT_APPLY       1034
#define IDC_CFGPATH_DEFAULT             1034
#define IDC_FILE_LIST_PATH_BROWSE       1034
#define IDC_PIC_CONV_OPTION_CHECK_RLE   1034
#define IDC_BATCH_RENAME_FORMAT_MENU    1034
#define IDC_SEARCH_START                1034
#define IDC_CFG_ADV_DEFAULT             1034
#define IDC_CFG_ADV_PATH_PROGRAM        1034
#define IDC_CFG_EXP_THUMB_CACHE_CLEAN   1034
#define IDC_FILTER_SET_APPLY_COLOR_CODE 1034
#define IDC_BUTTON4                     1035
#define IDC_CONFIGURATION1              1035
#define IDC_LISTREMOVE                  1035
#define IDC_FOLDER_MODIFY               1035
#define IDC_ADD_FILE_SCRAP              1035
#define IDC_CLEAR_CHACHE                1035
#define IDC_BUTTON_APPLY6               1035
#define IDC_SPLIT                       1035
#define IDC_BATCH_RENAME_BATCH_FORMAT_ARCHIVE 1035
#define IDC_BMK_ITEM_EDIT_STARTUP_BROWSE 1035
#define IDC_FILE_LIST_SEPARATOR         1035
#define IDC_CFG_EXP_DISP_SHOW_EACH_DRIVE 1035
#define IDC_CFG_EXP_THUMB_CACHE_INIT    1035
#define IDC_CFG_GENERAL_SHOW_TOOLTIP_WITH_NAME 1035
#define IDC_CFG_EXP_VIEW_NO_SORT        1035
#define IDC_FILE_SCRAP_CLEAR            1035
#define IDC_BG_COLOR                    1036
#define IDC_CONFIGURATION2              1036
#define IDC_DELETE                      1036
#define IDC_OPTION                      1036
#define IDC_FOLDER_DELETE               1036
#define IDC_BATCH_RENAME_UNDO           1036
#define IDC_FILE_SPLIT_OPTION           1036
#define IDC_FILE_SPLIT_GROUP_OPTION     1036
#define IDC_CFG_ADV_OPTION              1036
#define IDC_CFG_EXP_DISP_SHOW_24_HOUR_FORMAT 1036
#define IDC_CFG_GENERAL_SHOW_PROTECTED_FILE 1036
#define IDC_CFG_EXP_VIEW_SAVE_VIEW_STYLE 1036
#define IDC_FILE_SCRAP_DELETE           1036
#define IDC_DC_PATH                     1037
#define IDC_EDIT1                       1037
#define IDC_CONFIGURATION3              1037
#define IDC_BROWSER_COUNT               1037
#define IDC_ALLREMOVE                   1037
#define IDC_PATH                        1037
#define IDC_THUMB_WIDTH                 1037
#define IDC_WIDTH                       1037
#define IDC_FOLDER_ITEM_HEIGHT          1037
#define IDC_PALLETE_TRANSPARENT         1037
#define IDC_INPUT_EDIT                  1037
#define IDC_FLT_NAME                    1037
#define IDC_EXT_NAME                    1037
#define IDC_SND_DIR1                    1037
#define IDC_LEFT_PATH                   1037
#define IDC_ATTR_DEPTH                  1037
#define IDC_COLUMN_WIDTH                1037
#define IDC_BMK_ITEM_EDIT_ICON_INDEX    1037
#define IDC_PIC_CONV_OPTION_PALLETE_TRANSPARENT 1037
#define IDC_BATCH_RENAME_BATCH_FORMAT   1037
#define IDC_BATCH_RENAME_SKIP_SPEC_CHAR 1037
#define IDC_BATCH_RENAME_CASE_SKIP_SPEC_CHAR 1037
#define IDC_CFG_EXP_DISP_SHOW_2_DIGITS_YEAR 1037
#define IDC_CFG_EXP_THUMB_WIDTH         1037
#define IDC_CFG_FUNC_NAME_COPY_SEPARATOR 1037
#define IDC_FILTER_SET_NAME             1037
#define IDC_FILE_ASS_SET_PROGRAM        1037
#define IDC_FILE_SCRAP_CLEAR_ALL        1037
#define IDC_NEW_NUMBER_START            1038
#define IDC_BUTTON3                     1038
#define IDC_CONFIGURATION4              1038
#define IDC_COPY_TO_FOLDER              1038
#define IDC_HEIGHT                      1038
#define IDC_WEBTAB_SIZE                 1038
#define IDC_START                       1038
#define IDC_QUALITY                     1038
#define IDC_REMOVE_RECENTFILELIST       1038
#define IDC_FLT_EXTS                    1038
#define IDC_EXT_EXTS                    1038
#define IDC_BATCH_RENAME_REDO           1038
#define IDC_EDIT3                       1038
#define IDC_SND_DIR2                    1038
#define IDC_RIGHT_PATH                  1038
#define IDC_DEST_DIR                    1038
#define IDC_CREATE_NUMBER_START         1038
#define IDC_FILE_SPLIT_DEST_DIR         1038
#define IDC_PIC_CONV_OPTION_QUALITY     1038
#define IDC_CFG_ADV_REMOVE_RECENT_FILELIST 1038
#define IDC_CFG_DISP_CUSTOM_FONT        1038
#define IDC_CFG_EXP_DISP_SHOW_DRIVE_ITEM 1038
#define IDC_CFG_EXP_THUMB_HEIGHT        1038
#define IDC_FILTER_SET_EXTS             1038
#define IDC_FILE_SCRAP_COPY_TO_FOLDER   1038
#define IDC_NEW_FORMAT                  1039
#define IDC_MOVE_TO_FOLDER              1039
#define IDC_STOP                        1039
#define IDC_COMPRESS_LEVEL              1039
#define IDC_CREATE_FORMAT               1039
#define IDC_PIC_CONV_OPTION_COMPRESS_LEVEL 1039
#define IDC_CFG_DISP_MENU_ANIMATION     1039
#define IDC_CFG_EXP_DISP_SHOW_DRIVE_USAGE 1039
#define IDC_FILE_SCRAP_MOVE_TO_FOLDER   1039
#define IDC_NEW_NUMBER_END              1040
#define IDC_UNDO                        1040
#define IDC_OFFSET                      1040
#define IDC_CUR_LOCATION                1040
#define IDC_CUSTOM_FOLDER_HILIGHT       1040
#define IDC_CREATE_NUMBER_END           1040
#define IDC_PIC_CONV_OPTION_OFFSET      1040
#define IDC_SEARCH_CUR_LOC              1040
#define IDC_CFG_FLD_WND_INACTIVE_HIGHLIGHT 1040
#define IDC_NEW_NUMBER_COUNT            1041
#define IDC_CHECKLISTBOX                1041
#define IDC_VALIDATE                    1041
#define IDC_CREATE_NUMBER_COUNT         1041
#define IDC_CFG_DISP_STANDARD_MENU_STYLE 1041
#define IDC_CFG_FLD_INIT_NO_EXPAND      1041
#define IDC_CFG_FUNC_RENAME_BATCH_RENAME_WITH_FOLDER 1041
#define IDC_FILE_SCRAP_VALIDATE         1041
#define IDC_NEW_PATH                    1042
#define IDC_MOVE_TO_FOLDER2             1042
#define IDC_CFG_DISP_PATHBAR_HIGHLIGHT  1042
#define IDC_CFG_FUNC_RENAME_BATCH_RENAME_ON_MULTI_SEL_ITEMS 1042
#define IDC_NEW_NUMBER_INCREASE         1043
#define IDC_CREATE_NUMBER_INCREASE      1043
#define IDC_CFG_FUNC_RENAME_BY_MOUSE    1043
#define IDC_LINK_LIST                   1045
#define IDC_LIST                        1045
#define IDC_EXT_LIST                    1045
#define IDC_GRP_LIST                    1045
#define IDC_TEXT_MERGE_LIST             1045
#define IDC_BOOKMARK_EDIT_LIST          1045
#define IDC_FILTER_SET_ICON_LIST        1045
#define IDC_EDIT2                       1046
#define IDC_BG_FILENAME                 1046
#define IDC_THUMB_HEIGHT                1046
#define IDC_SPLIT_CHAR                  1046
#define IDC_DIV_TEXT                    1046
#define IDC_FILTER_INCLUDE              1046
#define IDC_ATTR_PATH                   1046
#define IDC_FILE_LIST_SEPARATOR_TEXT    1046
#define IDC_FOLDER_SYNC_SCAN_INCLUDE_FILTER 1046
#define IDC_CFG_DISP_CUSTOM_FONT_TEXT   1046
#define IDC_CFG_EXP_WND_BKGND_IMAGE_PATH 1046
#define IDC_CFG_FUNC_DRAG_DIST_DRAG_VALUE 1046
#define IDC_FILTER_SET_COLOR_CODE       1046
#define IDC_BUTTON6                     1047
#define IDC_FILTER_EXCLUDE              1047
#define IDC_FOLDER_SYNC_SCAN_EXCLUDE_FILTER 1047
#define IDC_CFG_FUNC_DRAG_FOLDER_EXPAND_TIME 1047
#define IDC_CFG_FUNC_DRAG_SCROLL_TIME   1048
#define IDC_MOUSE0                      1049
#define IDC_CFG_GENERAL_ONE_CLICK       1049
#define IDC_DEFAULT_RECOVERY            1050
#define IDC_CFG_GENERAL_DEFAULT         1050
#define IDC_CUSTOMFOLDER0               1051
#define IDC_CFG_FUNC_RENAME_EXT_DEFAULT 1051
#define IDC_CUSTOMFOLDER1               1052
#define IDC_CFG_FUNC_RENAME_SINGLE_RENAME_DEFAULT 1052
#define IDC_CUSTOMFOLDER2               1053
#define IDC_FOLDER                      1054
#define IDC_SHOW_NO                     1054
#define IDC_BMK_ITEM_EDIT_PATH          1054
#define IDC_BG_FIND                     1055
#define IDC_BG_SEARCH                   1055
#define IDC_FOLDER2                     1055
#define IDC_BMK_ITEM_EDIT_PARAM         1055
#define IDC_CFG_EXP_WND_BKGND_IMAGE_BROWSE 1055
#define IDC_BMK_ITEM_EDIT_STARTUP       1056
#define IDC_BMK_ITEM_EDIT_ICON_PATH     1057
#define IDC_LABEL                       1059
#define IDC_SHOW_TRAY                   1061
#define IDC_CFG_EXP_WND_INIT_FOLDER_BROWSE 1061
#define IDC_BROWSER_SPIN                1064
#define IDC_ADDRESS1                    1065
#define IDC_ADDRESS2                    1066
#define IDC_ADDRESS3                    1067
#define IDC_STATUS                      1067
#define IDC_ADDRESS4                    1068
#define IDC_TIME                        1068
#define IDC_SEARCH_TIME                 1068
#define IDC_ADDRESS5                    1069
#define IDC_EXPLORER                    1069
#define IDC_ADDRESS6                    1070
#define IDC_WEBTAB_SPIN                 1071
#define IDC_UNDERLINE                   1075
#define IDC_FILE_SCRAP_UNDERLINE        1075
#define IDC_THUMB_WIDTH_SPIN            1076
#define IDC_THUMB_HEIGHT_SPIN           1077
#define IDC_HOTKEY                      1078
#define IDC_CREATE_SHORTCUT_HOTKEY      1078
#define IDC_WIDTH_SPIN                  1080
#define IDC_CFG_EXP_THUMB_WIDTH_SPIN    1080
#define IDC_HEIGHT_SPIN                 1081
#define IDC_CFG_EXP_THUMB_HEIGHT_SPIN   1081
#define IDC_SIZE_UNIT                   1082
#define IDC_LIST_TYPE                   1083
#define IDC_FRONT_PATH                  1084
#define IDC_FILE_LIST_WITH_DIR          1084
#define IDC_CFG_EXP_DISP_ITEM_TEXT_CASE 1084
#define IDC_PRIORITY                    1085
#define IDC_CFG_EXP_THUMB_PRIORITY      1085
#define IDC_SLIDER1                     1086
#define IDC_QUALITY_SLIDER              1086
#define IDC_PIC_CONV_OPTION_QUALITY_SLIDER 1086
#define IDC_SLIDER2                     1087
#define IDC_THUMBNAIL_SIZE              1088
#define IDC_COMPATIBLE                  1089
#define IDC_CFG_EXP_THUMB_SUPPORTED_IMAGE 1089
#define IDC_PROGRESS                    1090
#define IDC_FILE_SPLIT_PROGRESS         1090
#define IDC_TOTAL_BYTE                  1091
#define IDC_DRIVE_TOTAL_BYTE            1091
#define IDC_TOTAL_UNIT                  1092
#define IDC_DRIVE_TOTAL_UNIT            1092
#define IDC_USING_BYTE                  1093
#define IDC_DRIVE_USED_BYTE             1093
#define IDC_USING_UNIT                  1094
#define IDC_DRIVE_USED_UNIT             1094
#define IDC_FREE_BYTE                   1095
#define IDC_DRIVE_FREE_BYTE             1095
#define IDC_FREE_UNIT                   1096
#define IDC_DRIVE_FREE_UNIT             1096
#define IDC_DRIVE                       1097
#define IDC_DRIVE_DRIVE                 1097
#define IDC_DRIVE_TYPE                  1099
#define IDC_DRIVE_FILESYSTEM            1100
#define IDC_DRIVE_ICON                  1101
#define IDC_DRIVE_LABEL                 1102
#define IDC_SHORTCUT_NAME               1104
#define IDC_SHOWCMD                     1111
#define IDC_CREATE_SHORTCUT_SHOWCMD     1111
#define IDC_NEXT                        1112
#define IDC_TIP_NEXT                    1112
#define IDC_COUNT                       1113
#define IDC_CFG_EXP_THUMB_LABEL_SUPPORTED_IMAGE_COUNT 1113
#define IDC_FLYEXPLORER                 1114
#define IDC_FOLDER_SPIN                 1117
#define IDC_SPIN_ITEM_HEIGHT            1117
#define IDC_OPEN_FOLDER                 1118
#define IDC_CFG_EXP_WND_INIT_FOLDER_PATH 1118
#define IDC_SEARCH_LIST                 1120
#define IDC_FOLDER_LIST                 1121
#define IDC_IS_ITEM_HEIGHT              1122
#define IDC_ITEM_HEIGHT                 1123
#define IDC_CFG_GENERAL_EXTENSION       1124
#define IDC_CFG_FUNC_RENAME_EXT_KEEP    1125
#define IDC_CFG_GENERAL_CREATE_BY_POPUP 1126
#define IDC_CFG_FUNC_RENAME_SINGLE_RENAME_BY_POPUP 1126
#define IDC_NOPOPUP                     1133
#define IDC_EXTERNAL_WEB                1134
#define IDC_SHOW_FAVORITEBAR            1135
#define IDC_CFG_FUNC_FILE_SCRAP_SAVE_SCRAP 1138
#define IDC_LOCATION                    1139
#define IDC_SEARCH_LOC                  1139
#define IDC_PIC_CONV_FORMAT             1142
#define IDC_LINE                        1146
#define IDC_SEARCH_LINE                 1146
#define IDC_LINE2                       1147
#define IDC_PIC_CONV_OPTION             1147
#define IDC_SEARCH_LINE2                1147
#define IDC_PIC_CONV_LIST               1148
#define IDC_PIC_CONV_PROGRESS           1149
#define IDC_PIC_CONV_STATUS             1150
#define IDC_PALLETE_TRANSPARENT_SPIN    1152
#define IDC_PIC_CONV_OPTION_PALLETE_TRANSPARENT_SPIN 1152
#define IDC_QUALITY_SPIN                1153
#define IDC_PIC_CONV_OPTION_QUALITY_SPIN 1153
#define IDC_PIC_CONV_OPTION_COMPRESS    1156
#define IDC_PIC_CONV_OPTION_LABEL_COMPRESS 1157
#define IDC_PIC_CONV_OPTION_COMPRESS_LEVEL_SPIN 1158
#define IDC_PIC_CONV_OPTION_LABEL_COMPRESS_LEVEL 1159
#define IDC_PIC_CONV_OPTION_LABEL_OFFSET 1160
#define IDC_PIC_CONV_OPTION_CHANNEL_ORDER 1161
#define IDC_PIC_CONV_OPTION_LABEL_CHANNEL_ORDER 1162
#define IDC_PIC_CONV_OPTION_CHANNEL_TYPE 1163
#define IDC_PIC_CONV_OPTION_LABEL_CHANNEL_TYPE 1164
#define IDC_PIC_CONV_OPTION_LABEL_QUALITY_STATIC 1165
#define IDC_PIC_CONV_OPTION_LABEL_QUALITY 1165
#define IDC_DRIVE_INFO                  1167
#define IDC_PIC_CONV_COLOR_BINARY       1168
#define IDC_PIC_CONV_COLOR_GRAYSCALE    1169
#define IDC_PIC_CONV_COLOR_COLOR        1170
#define IDC_PIC_CONV_COLOR_RADIO_BINARY 1172
#define IDC_PIC_CONV_COLOR_RADIO_COLOR  1174
#define IDC_ABOUT_VERSION               1175
#define IDC_PIC_CONV_COLOR_RADIO_TRUECOLOR 1175
#define IDC_SEARCH_TYPE                 1180
#define IDC_TEXT_MERGE_PROGRESS         1181
#define IDC_TEXT_MERGE_STATUS           1182
#define IDC_TEXT_MERGE_ITEM_DOWN        1183
#define IDC_TEXT_MERGE_ITEM_UP          1184
#define IDC_BATCH_RENAME_ITEM_MOVE      1185
#define IDC_TEXT_MERGE_ENCODING         1186
#define IDC_COMBOBOXEX1                 1187
#define IDC_LINK_ITEM_UP                1188
#define IDC_BOOKMARK_EDIT_ITEM_UP       1188
#define IDC_LINK_ITEM_DOWN              1189
#define IDC_BOOKMARK_EDIT_ITEM_DOWN     1189
#define IDC_LINK_ITEM_ADD               1190
#define IDC_BOOKMARK_EDIT_ITEM_ADD      1190
#define IDC_LINK_ITEM_MODIFY            1191
#define IDC_BOOKMARK_EDIT_ITEM_MODIFY   1191
#define IDC_LINK_ITEM_DELETE            1192
#define IDC_ITEM_CHECK                  1192
#define IDC_COLUMN_ITEM_SHOW            1192
#define IDC_BOOKMARK_EDIT_ITEM_DELETE   1192
#define IDC_LINK_QUICK_LAUNCH           1193
#define IDC_LINK_ITEM_ADD4              1193
#define IDC_ITEM_UNCHECK                1193
#define IDC_COLUMN_ITEM_HIDE            1193
#define IDC_BOOKMARK_EDIT_QUICK_LAUNCH  1193
#define IDC_LINK_DEFAULT                1194
#define IDC_BOOKMARK_EDIT_DEFAULT       1194
#define IDC_NEW_NUMBER_START_SPIN       1195
#define IDC_CREATE_NUMBER_START_SPIN    1195
#define IDC_NEW_NUMBER_END_SPIN         1196
#define IDC_CREATE_NUMBER_END_SPIN      1196
#define IDC_NEW_NUMBER_INCREASE_SPIN    1197
#define IDC_ITEM_ALL_CHECK              1197
#define IDC_CREATE_NUMBER_INCREASE_SPIN 1197
#define IDC_COLUMN_ITEM_SHOW_ALL        1197
#define IDC_NEW_NUMBER_COUNT_SPIN       1198
#define IDC_ITEM_ALL_UNCHECK            1198
#define IDC_CREATE_NUMBER_COUNT_SPIN    1198
#define IDC_COLUMN_ITEM_ALL_UNCHECK     1198
#define IDC_COLUMN_ITEM_HIDE_ALL        1198
#define IDC_NEW_IS_NUMBER_COUNT         1199
#define IDC_CREATE_IS_NUMBER_COUNT      1199
#define IDC_BATCH_RENAME_CASE           1199
#define IDC_NEW_IS_NUMBER_END           1200
#define IDC_ITEM_ALL_CHECK2             1200
#define IDC_CREATE_IS_NUMBER_END        1200
#define IDC_LINK_COLOR                  1201
#define IDC_CFG_CONTENTS_BOOKMARK_COLOR 1201
#define IDC_WU_PATH                     1205
#define IDC_SPC_PATH                    1205
#define IDC_SHARED_PROC_PATH            1205
#define IDC_WU_LIST                     1206
#define IDC_SPC_LIST                    1206
#define IDC_SHARED_PROC_LIST            1206
#define IDC_WU_STATUS                   1207
#define IDC_SPC_STATUS                  1207
#define IDC_SHARED_PROC_STATUS          1207
#define IDC_LINK_STATUS                 1208
#define IDC_BOOKMARK_EDIT_STATUS        1208
#define IDC_LINK_LINE                   1209
#define IDC_BOOKMARK_EDIT_LINE          1209
#define IDC_CFG_FUNC_FILE_ASS_DEFAULT   1211
#define IDC_DOS_COMMAND                 1214
#define IDC_FILE_SPLIT_OPTION_SPLIT_SIZE 1215
#define IDC_SEARCH_LOC_EDIT_INCLUDE     1215
#define IDC_SIZE_FORMAT_DEFAULT_DECIMAL_DIGIT 1215
#define IDC_SIZE_FORMAT_DEFAULT_DECIMAL_DIGITS 1215
#define IDC_CFG_EXP_FILTER_TEXT_COLOR   1215
#define IDC_FILE_ASS_SET_METHOD_EXT     1215
#define IDC_RADIO2                      1216
#define IDC_SI_BROWSE                   1216
#define IDC_EXCLUDE                     1216
#define IDC_OPTION_SPLIT_COUNT          1216
#define IDC_ASS_FILTER                  1216
#define IDC_NUMDIGITS_CUSTOM            1216
#define IDC_FILE_SPLIT_OPTION_SPLIT_COUNT 1216
#define IDC_SEARCH_LOC_EDIT_EXCLUDE     1216
#define IDC_SIZE_FORMAT_CUSTOM_DECIMAL_DIGIT 1216
#define IDC_SIZE_FORMAT_CUSTOM_DECIMAL_DIGITS 1216
#define IDC_CFG_EXP_FILTER_BACKGROUND_COLOR 1216
#define IDC_CFG_FUNC_DRAG_CTRL_DRAG     1216
#define IDC_FILE_ASS_SET_METHOD_FILTER  1216
#define IDC_BATCH_RENAME_PATH           1217
#define IDC_CFG_STYLE_ADVANCED          1217
#define IDC_CFG_FUNC_DRAG_DIST_DRAG     1217
#define IDC_CFG_FUNC_DRAG_DEFAULT_DRAG  1218
#define IDC_BATCH_RENAME_BACKUP         1219
#define IDC_CFG_FUNC_DRAG_NO_DROP       1219
#define IDC_BATCH_RENAME_INSERT_TYPE    1220
#define IDC_CFG_FUNC_DRAG_DEFAULT_DROP  1220
#define IDC_CB_TEXTTYPE                 1221
#define IDC_BATCH_RENAME_DELETE_TYPE    1221
#define IDC_CUSTOM_TOOLBAR_TEXT_OPTION  1221
#define IDC_BATCH_RENAME_NO_CHANGE_EXT  1222
#define IDC_CB_ICONTYPE                 1222
#define IDC_CUSTOM_TOOLBAR_ICON_OPTION  1222
#define IDC_CUSTOM_FOLDER               1224
#define IDC_CFG_FLD_WND_CUSTOM_FOLDER   1224
#define IDC_DRV_TREE                    1225
#define IDC_CUSTOM_EXPLORER             1225
#define IDC_DRIVE_TREE                  1225
#define IDC_CFG_FLD_WND_CUSTOM_EXPLORER 1225
#define IDC_CUSTOM_NONE                 1226
#define IDC_BMK_ITEM_EDIT_NAME          1226
#define IDC_CFG_FLD_WND_CUSTOM_NONE     1226
#define IDC_BMK_ITEM_EDIT_PATH_BROWSE   1227
#define IDC_BMK_ITEM_EDIT_HOTKEY        1228
#define IDC_KEY_CATEGORY                1229
#define IDC_ACCEL_CATEGORY              1229
#define IDC_BMK_ITEM_EDIT_ICON_BROWSE   1229
#define IDC_KEY_CURRENT_KEY             1230
#define IDC_ACCEL_CUR_KEYS              1230
#define IDC_KEY_HOTKEY                  1231
#define IDC_ACCEL_HOTKEY                1231
#define IDC_KEY_DEFINED                 1232
#define IDC_ACCEL_ASSIGNED_TO           1232
#define IDC_KEY_COMMAND                 1233
#define IDC_ACCEL_COMMANDS              1233
#define IDC_KEY_ASSIGN                  1234
#define IDC_ACCEL_BUTTON_ASSIGN         1234
#define IDC_KEY_REMOVE                  1235
#define IDC_ACCEL_BUTTON_REMOVE         1235
#define IDC_BATCH_RENAME_PROGRESS       1235
#define IDC_KEY_ALL_RESET               1236
#define IDC_ACCEL_BUTTON_RESET_ALL      1236
#define IDC_BATCH_RENAME_STATUS         1236
#define IDC_KEY_DESCRIPTION             1237
#define IDC_WEBTAB_POS                  1237
#define IDC_ACCEL_DESC                  1237
#define IDC_INFO                        1238
#define IDC_KEY_ALL_RESET2              1238
#define IDC_KEY_RESET                   1238
#define IDC_ACCEL_BUTTON_RESET          1238
#define IDC_SEL_NAME_DESC               1238
#define IDC_SAVE_WEBVIEW                1239
#define IDC_CRC_BROWSE                  1241
#define IDC_CRCCREATE_BROWSE            1241
#define IDC_CRC_FILE                    1242
#define IDC_CRC_PATH                    1242
#define IDC_CRCVERIFY_PATH              1242
#define IDC_COMBINE_CRC_FILE            1242
#define IDC_CFG_FUNC_FILE_SCRAP_SHOW_POPUP 1242
#define IDC_CRC_METHOD                  1243
#define IDC_CRCCREATE_METHOD            1243
#define IDC_CRC_LIST                    1244
#define IDC_CRCVERIFY_LIST              1244
#define IDC_CRC_PROGRESS                1245
#define IDC_CRCVERIFY_PROGRESS          1245
#define IDC_CRC_STATUS                  1246
#define IDC_CRCVERIFY_STATUS            1246
#define IDC_NEW_FORMAT_MENU             1248
#define IDC_CREATE_FORMAT_MENU          1248
#define IDC_CFG_STYLE_NORMAL            1249
#define IDC_BATCH_RENAME_CASE_TYPE      1250
#define IDC_CFG_EXP_WND_LABEL_BKGND_IMAGE 1254
#define IDC_CFG_EXP_WND_LABEL_TEXT_COLOR 1255
#define IDC_CFG_EXP_WND_TEXT_COLOR      1256
#define IDC_CFG_EXP_WND_LABEL_BKGND_COLOR 1257
#define IDC_CFG_EXP_WND_BKGND_COLOR     1258
#define IDC_INPUT_DESC                  1268
#define IDC_INPUT_LABEL_DESC            1268
#define IDC_SEL_ONLY                    1275
#define IDC_SEL_NAME_SEL_ONLY           1275
#define IDC_SEL_NAME                    1276
#define IDC_CFG_EXP_FILTER_USE_COLOR    1278
#define IDC_CFG_EXP_FILTER_LIST         1279
#define IDC_CFG_EXP_FILTER_ADD          1280
#define IDC_CFG_EXP_FILTER_MODIFY       1281
#define IDC_CFG_EXP_FILTER_DELETE       1282
#define IDC_CFG_EXP_FILTER_LABEL_MAX_FILTER 1283
#define IDC_FLT_COLOR                   1284
#define IDC_EXT_COLOR                   1284
#define IDC_FILTER_SET_COLOR            1284
#define IDC_CFG_EXP_FILTER_ITEM_UP      1285
#define IDC_CFG_EXP_FILTER_ITEM_DOWN    1286
#define IDC_BMK_ITEM_EDIT_CUSTOM_ICON   1291
#define IDC_BMK_ITEM_EDIT_LABEL_ICON    1292
#define IDC_BMK_ITEM_EDIT_ICON_INDEX_STATIC 1293
#define IDC_BMK_ITEM_EDIT_LABEL_ICON_INDEX 1293
#define IDC_BMK_ITEM_EDIT_SMALL_ICON    1296
#define IDC_RENAME_EDIT_OLD_NAME_EDIT   1307
#define IDC_RENAME_EDIT_NEW_NAME_EDIT   1308
#define IDC_RENAME_EDIT_SYNC_SCROLL     1309
#define IDC_RENAME_EDIT_LABEL_ARROW     1310
#define IDC_RENAME_EDIT_LABEL_NEW_NAME  1311
#define IDC_ATTR_ARCHIVE                1312
#define IDC_ATTR_READONLY               1313
#define IDC_ATTR_HIDDEN                 1314
#define IDC_ATTR_SYSTEM                 1315
#define IDC_ATTR_CREATION               1316
#define IDC_ATTR_MODIFIED               1317
#define IDC_ATTR_CREATION_DATE          1318
#define IDC_ATTR_CREATION_TIME          1319
#define IDC_ATTR_MODIFIED_DATE          1320
#define IDC_ATTR_MODIFIED_TIME          1321
#define IDC_ATTR_ACCESS_DATE            1322
#define IDC_ATTR_ACCESS_TIME            1323
#define IDC_ATTR_ACCESS                 1324
#define IDC_ATTR_SUBFOLDER              1326
#define IDC_ATTR_LIST                   1329
#define IDC_ATTR_PROGRESS               1330
#define IDC_ATTR_STATUS                 1331
#define IDC_ATTR_TIME                   1332
#define IDC_ATTR_ATTRIBUTE              1333
#define IDC_CFG_EXP_DISP_SHOW_LIST_TYPE 1333
#define IDC_SIZE_UNIT_MULTIPLE_FILE     1334
#define IDC_CFG_DISP_SIZE_MULTIPLE_ITEMS_UNIT 1334
#define IDC_CFG_EXP_DISP_SIZE_UNIT      1334
#define IDC_CFG_EXP_DISP_SHOW_ATTR_ARHS_STYLE 1335
#define IDC_CFG_CONTENTS_SHOW_ATTR_ARHS_STYLE 1335
#define IDC_CFG_EXP_DISP_SHOW_PARENT_FOLDER 1336
#define IDC_CFG_DISP_ACTIVE_VIEW_COLOR  1337
#define IDC_CFG_DISP_PATHBAR_HIGHLIGHT_COLOR 1338
#define IDC_CFG_FUNC_BOOKMARK_EXPAND_FOLDER 1338
#define IDC_CFG_DISP_CUSTOM_FONT_TEXT_BROWSE 1339
#define IDC_CFG_FUNC_BOOKMARK_REAL_PATH 1339
#define IDC_CFG_EXP_WND_CUSTOMIZE_FOLDER 1341
#define IDC_CFG_FUNC_REFRESH_NO_REFRESH 1342
#define IDC_CFG_FUNC_SPLIT_FOCUS_MOVE_BY_TAB 1343
#define IDC_CFG_FUNC_REFRESH_AUTO_SORT  1344
#define IDC_CFG_FUNC_SPLIT_RESIZE_BY_RATIO 1345
#define IDC_CFG_FUNC_DRIVE_LAST_FOLDER  1346
#define IDC_CFG_FUNC_SPLIT_SINGLE_SPLIT_VIEW_CHANGE_THROUGH_ACTIVED_VIEW 1346
#define IDC_CFG_FUNC_DRAG_NO_DRAG       1347
#define IDC_CFG_FUNC_SPLIT_SPLIT_LAST_FOLDER 1347
#define IDC_CFG_FUNC_INET_ADDR_COMPATIBLE 1348
#define IDC_CFG_EXP_DISP_USE_CUSTOM_ICON 1349
#define IDC_CFG_FUNC_CLEAR_SEARCH_RESULT 1349
#define IDC_CFG_EXP_DISP_CUSTOM_ICON_16_PATH 1350
#define IDC_CFG_FUNC_FILE_OP_COMPLETED_FLASH_TASKBAR 1350
#define IDC_CFG_EXP_DISP_CUSTOM_ICON_16_PATH_BROWSE 1351
#define IDC_CFG_FUNC_DRIVE_SHIFT_KEY    1351
#define IDC_FOLDER_SYNC_PATH2_BROWSE    1352
#define IDC_CFG_EXP_DISP_CUSTOM_ICON_32_PATH 1352
#define IDC_CFG_FUNC_SHELL_NEW          1352
#define IDC_CFG_EXP_DISP_CUSTOM_ICON_32_PATH_BROWSE 1353
#define IDC_CFG_FUNC_FILELIST_CUR_DIR   1353
#define IDC_CFG_EXP_EDIT_AFTER_CREATING_TEXT 1354
#define IDC_CFG_DISP_PATHBAR_REAL_PATH  1355
#define IDC_CFG_EXP_VIEW_AUTO_COLUMN_WIDTH 1355
#define IDC_CFG_FUNC_WORKING_FOLDER_REAL_PATH 1355
#define IDC_CFG_FUNC_FILE_OP_EXTERNAL_MOVE 1355
#define IDC_CFG_DISP_PATHBAR_ICON       1356
#define IDC_CFG_EXP_VIEW_CLEAN_ON_EXIT  1356
#define IDC_CFG_FUNC_FILE_OP_EXTERNAL_DELETE 1356
#define IDC_BMK_ITEM_EDIT_SHOW          1358
#define IDC_CFG_FUNC_DRAG_DIST_DRAG_SPIN 1361
#define IDC_CFG_FLD_SINGLE_FOLDER_PANE_LINKAGE 1362
#define IDC_CFG_FUNC_DRAG_EXPAND_FOLDER_TIME_SPIN 1362
#define IDC_BATCH_RENAME_ITEM_UP        1363
#define IDC_CFG_FUNC_DRAG_SCROLL_TIME_SPIN 1363
#define IDC_BATCH_RENAME_ITEM_DOWN      1364
#define IDC_GO_PATH_PATH                1365
#define IDC_BATCH_RENAME_TAB            1366
#define IDC_ATTR_DEPTH_SPIN             1368
#define IDC_ATTR_TYPE                   1369
#define IDC_BATCH_RENAME_LABEL_BACKUP   1370
#define IDC_BATCH_RENAME_FORMAT_NAME    1371
#define IDC_BATCH_RENAME_FORMAT_AUTO_NUM 1372
#define IDC_CFG_FUNC_DRAG_LABEL_DIST_DRAG_RANGE 1372
#define IDC_BATCH_RENAME_FORMAT_DATE    1373
#define IDC_BATCH_RENAME_REPLACE_NOTCASE 1373
#define IDC_BATCH_RENAME_REPLACE_NOCASE 1373
#define IDC_CFG_FUNC_DRAG_LABEL_EXPAND_FOLDER_TIME_RANGE 1373
#define IDC_BATCH_RENAME_FORMAT_TIME    1374
#define IDC_CFG_FUNC_DRAG_LABEL_SCROLL_TIME_RANGE 1374
#define IDC_BATCH_RENAME_FORMAT_EXT     1375
#define IDC_CFG_FUNC_DRAG_DEFAULT_OPERATION 1376
#define IDC_CFG_EXP_VIEW_DEFAULT_VIEW_STYLE 1377
#define IDC_CFG_EXP_VIEW_DEFAULT_SORT   1378
#define IDC_CFG_EXP_VIEW_DEFAULT_SORT_ORDER 1379
#define IDC_PARAM_EXEC_PATH             1381
#define IDC_PARAM_EXEC_PARAMETER        1382
#define IDC_SPLIT_SIZE_TEMPLATE         1383
#define IDC_ACCEL_VIRTUAL               1383
#define IDC_FILE_SPLIT_SIZE_PRESET      1383
#define IDC_FOLDER_SYNC_OPTION_PATH1    1383
#define IDC_FILE_ASS_SET_FILTER         1383
#define IDC_SPLIT_SIZE_UNIT             1384
#define IDC_FILE_SPLIT_SIZE_UNIT        1384
#define IDC_FOLDER_SYNC_OPTION_PATH2    1384
#define IDC_DIRECTION                   1385
#define IDC_SND_STATUS                  1385
#define IDC_SPLIT_COUNT                 1385
#define IDC_FILE_SPLIT_COUNT            1385
#define IDC_FOLDER_SYNC_OPTION_DIRECTION 1385
#define IDC_SND_LIST                    1386
#define IDC_SPLIT_SIZE                  1386
#define IDC_FILE_SPLIT_SIZE             1386
#define IDC_NEW_NAME                    1387
#define IDC_CFG_EXP_WND_NO_LAST_NET_FOLDER 1389
#define IDC_CFG_FUNC_DRAG_DRAGGING_NO_CONTENTS 1390
#define IDC_MODIFY                      1392
#define IDC_SIZE_FORMAT_MODIFY          1392
#define IDC_CFG_FLD_CUSTOM_FONT         1394
#define IDC_CFG_FLD_CUSTOM_FONT_TEXT    1395
#define IDC_CFG_FLD_CUSTOM_FONT_TEXT_BROWSE 1396
#define IDC_CFG_FLD_ITEM_HEIGHT         1397
#define IDC_CFG_FLD_ITEM_HEIGHT_SIZE    1398
#define IDC_CFG_FLD_ITEM_HEIGHT_SIZE_SPIN 1399
#define IDC_CFG_FLD_EXPLORE_DELAY       1400
#define IDC_URL                         1401
#define IDC_GO_URL                      1401
#define IDC_GO_PATH_URL                 1401
#define IDC_CFG_FLD_EXPLORE_DELAY_TIME  1401
#define IDC_HISTORY_COUNT               1402
#define IDC_CFG_FLD_EXPLORE_DELAY_TIME_SPIN 1402
#define IDC_CFG_FUNC_HISTORY_HISTORY_COUNT 1402
#define IDC_HISTORY_COUNT_SPIN          1403
#define IDC_CFG_FUNC_HISTORY_HISTORY_COUNT_SPIN 1403
#define IDC_HISTORY_COUNT_INFO          1404
#define IDC_CFG_FUNC_HISTORY_LABEL_HISTORY_COUNT_RANGE 1404
#define IDC_BACKWARD_COUNT              1405
#define IDC_CFG_FUNC_HISTORY_BACKWARD_COUNT 1405
#define IDC_BACKWARD_COUNT_SPIN         1406
#define IDC_CFG_FUNC_HISTORY_BACKWARD_COUNT_SPIN 1406
#define IDC_BACKWARD_COUNT_INFO         1407
#define IDC_BMK_ITEM_EDIT_SEPARATOR     1407
#define IDC_CFG_FUNC_HISTORY_LABEL_BACKWARD_COUNT_RANGE 1407
#define IDC_HISTORY_MENU_COUNT          1408
#define IDC_CFG_EXP_VIEW_NONE           1408
#define IDC_CFG_FUNC_HISTORY_HISTORY_MENU_COUNT 1408
#define IDC_HISTORY_MENU_COUNT_SPIN     1409
#define IDC_CFG_EXP_VIEW_DEFAULT        1409
#define IDC_CFG_FUNC_HISTORY_HISTORY_MENU_COUNT_SPIN 1409
#define IDC_HISTORY_MENU_COUNT_INFO     1410
#define IDC_BATCH_RENAME_FORMAT_NUMBER_ZERO 1410
#define IDC_CFG_FUNC_HISTORY_LABEL_HISTORY_MENU_COUNT_RANGE 1410
#define IDC_NEW_NUMBER_LENGTH           1411
#define IDC_BACKWARD_MENU_COUNT         1411
#define IDC_CREATE_NUMBER_LENGTH        1411
#define IDC_CFG_FUNC_HISTORY_BACKWARD_MENU_COUNT 1411
#define IDC_NEW_NUMBER_LENGTH_SPIN      1412
#define IDC_BACKWARD_MENU_COUNT_SPIN    1412
#define IDC_CREATE_NUMBER_LENGTH_SPIN   1412
#define IDC_CFG_FUNC_HISTORY_BACKWARD_MENU_COUNT_SPIN 1412
#define IDC_NEW_NUMBER_ZERO             1413
#define IDC_BACKWARD_MENU_COUNT_INFO    1413
#define IDC_CREATE_NUMBER_ZERO          1413
#define IDC_CFG_FUNC_HISTORY_LABEL_BACKWARD_MENU_COUNT_RANGE 1413
#define IDC_NEW_FORMAT_AUTO_NUM         1414
#define IDC_CREATE_FORMAT_AUTO_NUM      1414
#define IDC_NEW_FORMAT_DATE             1415
#define IDC_CREATE_FORMAT_DATE          1415
#define IDC_NEW_FORMAT_TIME             1416
#define IDC_CREATE_FORMAT_TIME          1416
#define IDC_CFG_EXP_VIEW_INIT           1417
#define IDC_SEARCH_LOC_STATUS           1418
#define IDC_CFG_EXP_VIEW_CLEAN          1418
#define IDC_SEARCH_LOC_ITEM_LIST        1419
#define IDC_SEARCH_LOC_ITEM_ADD         1420
#define IDC_SEARCH_LOC_ITEM_MODIFY      1421
#define IDC_SEARCH_LOC_ITEM_DELETE      1422
#define IDC_SEARCH_LOC_ITEM_UP          1423
#define IDC_SEARCH_LOC_ITEM_DOWN        1424
#define IDC_CFG_FLD_LABEL_EXPLORE_DELAY_TIME_RANGE 1426
#define IDC_SEARCH_LOC_LIST             1427
#define IDC_SEARCH_LOC_LIST_NEW         1428
#define IDC_SEARCH_LOC_LABEL_LIST       1429
#define IDC_LIST_LABEL                  1431
#define IDC_FILE_SCRAP__LIST_LABEL      1431
#define IDC_FILE_SCRAP_LIST_LABEL       1431
#define IDC_SIZE_UNIT_SINGLE_FILE       1432
#define IDC_CFG_DISP_SIZE_SINGLE_ITEM_UNIT 1432
#define IDC_FILE_ASS_PROGRAM_BROWSE     1433
#define IDC_FILE_ASS_SET_PROGRAM_BROWSE 1433
#define IDC_GO_PATH_PATH_BROWSE         1435
#define IDC_ACCEL_CTRL                  1436
#define IDC_COMPARE_DATETIME            1437
#define IDC_ACCEL_ALT                   1437
#define IDC_FOLDER_SYNC_COMPARE_BY_DATETIME 1437
#define IDC_COMPARE_ATTRIBUTES          1438
#define IDC_ACCEL_SHIFT                 1438
#define IDC_FOLDER_SYNC_COMPARE_BY_ATTRIBUTES 1438
#define IDC_COMPARE_CONTENTS            1439
#define IDC_FOLDER_SYNC_COMPARE_BY_CONTENTS 1439
#define IDC_FILTER_BOTH_EXCLUDE         1440
#define IDC_FOLDER_SYNC_SCAN_EXCLUDE_EQUAL_FILENAME 1440
#define IDC_FILTER_SIDE_EXCLUDE         1441
#define IDC_FOLDER_SYNC_SCAN_EXCLUDE_OTHER_FILENAME 1441
#define IDC_COMPARE_SIZE                1442
#define IDC_FOLDER_SYNC_COMPARE_BY_SIZE 1442
#define IDC_FILTER_SYSTEM               1443
#define IDC_FOLDER_SYNC_SCAN_SYSTEM     1443
#define IDC_FILTER_HIDDEN               1444
#define IDC_FOLDER_SYNC_SCAN_HIDDEN     1444
#define IDC_FOLDER_SYNC_PATH1_BROWSE    1445
#define IDC_SYNCHRONIZE                 1446
#define IDC_FOLDER_SYNC_SYNCHRONIZE     1446
#define IDC_FILTER_SUBFOLDER            1447
#define IDC_FOLDER_SYNC_SCAN_SUBFOLDER  1447
#define IDC_TO_RIGHT                    1449
#define IDC_FOLDER_SYNC_OPTION_TO_RIGHT 1449
#define IDC_TO_LEFT                     1450
#define IDC_DIFF_PREV                   1450
#define IDC_FOLDER_SYNC_PREV_DIFF       1450
#define IDC_FOLDER_SYNC_OPTION_TO_LEFT  1450
#define IDC_DIFF_NEXT                   1451
#define IDC_FOLDER_SYNC_NEXT_DIFF       1451
#define IDC_PATH_BROWSE                 1452
#define IDC_FILE_SPLIT_PATH_BROWSE      1452
#define IDC_DEST_DIR_BROWSE             1453
#define IDC_FILE_SPLIT_DEST_DIR_BROWSE  1453
#define IDC_FILE_SIZE                   1454
#define IDC_FILE_SPLIT_FILE_SIZE        1454
#define IDC_FILE_SPLIT_LABEL_FILE_SIZE  1454
#define IDC_SPLIT_CRC                   1455
#define IDC_FILE_SPLIT_WITH_CRC         1455
#define IDC_SPLIT_DELORG                1456
#define IDC_FILE_SPLIT_DELETE_ORG       1456
#define IDC_SPLIT_BATCH                 1457
#define IDC_FILE_SPLIT_CREATE_BATCH_FILE 1457
#define IDC_ITEM_UP                     1459
#define IDC_MERGE_ITEM_UP               1459
#define IDC_ITEM_DOWN                   1460
#define IDC_MERGE_ITEM_DOWN             1460
#define IDC_DEST_FILE                   1461
#define IDC_MERGE_DEST_FILE             1461
#define IDC_DEST_FILE_BROWSE            1462
#define IDC_MERGE_DEST_FILE_BROWSE      1462
#define IDC_CFG_FUNC_FILE_ASS_LABEL_LIMIT_COUNT 1463
#define IDC_CFG_FUNC_FILE_ASS_LIST      1464
#define IDC_CFG_FUNC_FILE_ASS_ITEM_ADD  1465
#define IDC_CFG_FUNC_FILE_ASS_ITEM_MODIFY 1466
#define IDC_CFG_FUNC_FILE_ASS_ITEM_DELETE 1467
#define IDC_CFG_FUNC_FILE_ASS_ITEM_DOWN 1468
#define IDC_CFG_FUNC_FILE_ASS_ITEM_UP   1469
#define IDC_EXTS                        1470
#define IDC_FILE_ASS_SET_EXTS           1470
#define IDC_ASS_VIEWER                  1471
#define IDC_FILE_ASS_SET_TYPE_VIEWER    1471
#define IDC_ASS_EDITOR                  1472
#define IDC_CFG_EXP_FILTER_DEFAULT      1472
#define IDC_FILE_ASS_SET_TYPE_EDITOR    1472
#define IDC_GROUP                       1473
#define IDC_FILE_SCRAP_GROUP            1473
#define IDC_GROUP_NEW                   1474
#define IDC_FILE_SCRAP_NEW_GROUP        1474
#define IDC_GROUP_LABEL                 1475
#define IDC_FILE_SCRAP_GROUP_LABEL      1475
#define IDC_COMBO2                      1477
#define IDC_UNIT                        1477
#define IDC_SIZE_FORMAT_UNIT            1477
#define IDC_UNIT_SIZE                   1478
#define IDC_SIZE_FORMAT_CUSTOM_EDIT     1478
#define IDC_SIZE_FORMAT_CUSTOM          1478
#define IDC_SIZE_FORMAT_UNIT_SIZE       1478
#define IDC_CFG_DISP_SIZE_CUSTOM_FORMAT 1478
#define IDC_SIZE_UNIT_STD               1479
#define IDC_DISPLAY                     1479
#define IDC_UNIT_DISP                   1479
#define IDC_SIZE_FORMAT_UNIT_DISP       1479
#define IDC_SIZE_UNIT_CUSTOM            1480
#define IDC_NUMDIGITS                   1480
#define IDC_SIZE_FORMAT_DECIMAL_DIGIT   1480
#define IDC_ADD                         1482
#define IDC_SIZE_FORMAT_ADD             1482
#define IDC_DOWN                        1483
#define IDC_SIZE_FORMAT_ITEM_DOWN       1483
#define IDC_UP                          1484
#define IDC_SIZE_FORMAT_ITEM_UP         1484
#define IDC_NUMDIGITS_SPIN              1486
#define IDC_SIZE_FORMAT_DECIMAL_DIGIT_SPIN 1486
#define IDC_ROUND_OFF                   1487
#define IDC_SIZE_FORMAT_ROUND_OFF       1487
#define IDC_SET_PATH                    1488
#define IDC_CFG_ADV_PATH_SET_PATH       1488
#define IDC_CFGPATH_APPDATA             1489
#define IDC_ALL_INIT                    1489
#define IDC_CFG_ADV_PATH_APPDATA        1489
#define IDC_CFGPATH_CUSTOM_PATH         1490
#define IDC_CFG_ADV_PATH_CUSTOM_PATH    1490
#define IDC_CFGPATH_CUSTOM_PATH_BROWSE  1491
#define IDC_CFG_ADV_PATH_CUSTOM_PATH_BROWSE 1491
#define IDC_CUSTOM_TEXT_COLOR           1495
#define IDC_CFG_FLD_WND_TEXT_COLOR      1495
#define IDC_CUSTOM_FOLDER_HILIGHT_COLOR 1496
#define IDC_CFG_FLD_WND_INACTIVE_HIGHLIGHT_COLOR 1496
#define IDC_INIT                        1497
#define IDC_EDIT                        1498
#define IDC_CREATE_EDIT                 1498
#define IDC_CFG_EXP_DISP_SHOW_GRID_LINES 1499
#define IDC_CFG_EXP_DISP_FULL_ROW_SELECTION 1500
#define IDC_CFG_LAUNCHER                1501
#define IDC_CFG_ADV_HOTKEY_LAUNCHER     1501
#define IDC_CFG_HOTKEY                  1502
#define IDC_CFG_ADV_HOTKEY_HOTKEY       1502
#define IDC_CFG_LAUNCHER_TRAY           1503
#define IDC_DESC_BKGND                  1503
#define IDC_CFG_ADV_HOTKEY_LAUNCHER_TRAY 1503
#define IDC_CFG_WIN_STARTUP             1504
#define IDC_CFG_LAUNCHER_WIN_STARTUP    1504
#define IDC_CFG_ADV_HOTKEY_LAUNCHER_WIN_STARTUP 1504
#define IDC_CFG_FUNC_HISTORY_SAVE_HISTROY 1504
#define IDC_CFG_FLD_WND_LABEL_TEXT_COLOR 1505
#define IDC_CFG_FUNC_FILE_OP_EXTERNAL_COPY 1505
#define IDC_CFG_FUNC_HISTORY_LABEL_BACKWARD_COUNT 1506
#define IDC_CFG_FUNC_HISTORY_LABEL_HISTORY_MENU_COUNT 1507
#define IDC_ABOUT_LABEL_ACCEPT          1507
#define IDC_CFG_FLD_WND_LABEL_BKGND_COLOR 1507
#define IDC_CFG_FUNC_HISTORY_LABEL_BACKWARD_MENU_COUNT 1508
#define IDC_ABOUT_SYSTEM                1508
#define IDC_CFG_FLD_WND_BKGND_COLOR     1508
#define IDC_CFG_FUNC_HISTORY_LABEL_HISTORY_COUNT 1509
#define IDC_ACCEL_LABEL_CATEGORY        1509
#define IDC_CFG_DESC                    1513
#define IDC_ACCEL_LABEL_ASSIGNED_TO     1515
#define IDC_ACCEL_LABEL_COMMANDS        1516
#define IDC_ACCEL_LABEL_CUR_KEYS        1517
#define IDC_ACCEL_LABEL_NEW_SHORTCUT_KEY 1518
#define IDC_ACCEL_LABEL_DESC            1519
#define IDC_ATTR_LABEL_PATH             1520
#define IDC_ATTR_LABEL_DEPTH            1521
#define IDC_ATTR_LABEL_TYPE             1522
#define IDC_CREATE_LABEL_PATH           1523
#define IDC_CREATE_PATH                 1524
#define IDC_CREATE_LABEL_TYPE           1525
#define IDC_CREATE_TYPE                 1526
#define IDC_CREATE_TAB                  1527
#define IDC_CREATE_PROGRESS             1528
#define IDC_CREATE_STATUS               1529
#define IDC_CREATE_LABEL_NUMBER         1530
#define IDC_CREATE_LABEL_NUMBER_INCREASE 1531
#define IDC_COLUMN_LIST                 1531
#define IDC_CREATE_LABEL_NUMBER_LENGTH  1532
#define IDC_COLUMN_ITEM_UP              1532
#define IDC_CREATE_LABEL_NUMBER_START   1533
#define IDC_COLUMN_ITEM_DOWN            1533
#define IDC_CREATE_LABEL_FORMAT         1534
#define IDC_COLUMN_LABEL_DESC           1534
#define IDC_COLUMN_LABEL_LIST           1535
#define IDC_COLUMN_LABEL_WIDTH          1536
#define IDC_CRCCREATE_LABEL_PATH        1537
#define IDC_CRCCREATE_PATH              1538
#define IDC_CRCCREATE_LABEL_METHOD      1539
#define IDC_CRCCREATE_LIST              1540
#define IDC_CRCCREATE_PROGRESS          1541
#define IDC_CRCCREATE_STATUS            1542
#define IDC_CRCVERIFY_LABEL_PATH        1543
#define IDC_CRCVERIFY_LABEL_LIST        1544
#define IDC_DOS_LABEL_PATH              1545
#define IDC_DOS_PATH                    1546
#define IDC_DOS_LABEL_INPUT             1547
#define IDC_DOS_LABEL_COMMAND           1548
#define IDC_DRIVE_LABEL_LABEL           1549
#define IDC_DRIVE_LABEL_TYPE            1550
#define IDC_DRIVE_LABEL_FILESYSTEM      1551
#define IDC_DRIVE_PROGRESS              1552
#define IDC_DRIVE_LABEL_FREE            1553
#define IDC_DRIVE_LABEL_USED            1554
#define IDC_DRIVE_LABEL_TOTAL           1555
#define IDC_FILEASS_FILE                1556
#define IDC_FILEASS_TREE                1557
#define IDC_FILEASS_STATUS              1558
#define IDC_FILEASS_LABEL_FILE          1559
#define IDC_COMBINE_LABEL_PATH          1559
#define IDC_COMBINE_PATH                1560
#define IDC_COMBINE_PATH_BROWSE         1561
#define IDC_COMBINE_LABEL_CRC_FILE      1562
#define IDC_COMBINE_LABEL_DEST_DIR      1563
#define IDC_COMBINE_DEST_DIR_BROWSE     1564
#define IDC_COMBINE_DEST_DIR            1565
#define IDC_COMBINE_PROGRESS            1566
#define IDC_COMBINE_STATUS              1567
#define IDC_MERGE_LABEL_PATH            1568
#define IDC_MERGE_PATH                  1569
#define IDC_MERGE_LABEL_FILES           1570
#define IDC_MERGE_LIST                  1571
#define IDC_MERGE_LABEL_DEST_FILE       1572
#define IDC_MERGE_PROGRESS              1573
#define IDC_MERGE_STATUS                1574
#define IDC_FILE_SPLIT_LABEL_PATH       1575
#define IDC_FILE_SPLIT_PATH             1576
#define IDC_FILE_SPLIT_LABEL_DEST_DIR   1577
#define IDC_FILE_SPLIT_STATUS           1578
#define IDC_GO_PATH_LABEL_INPUT         1579
#define IDC_LINK_LABEL_LIST             1580
#define IDC_BOOKMARK_EDIT_LABEL_LIST    1580
#define IDC_BMK_ITEM_EDIT_LABEL_NAME    1581
#define IDC_BMK_ITEM_EDIT_LABEL_PATH    1582
#define IDC_BMK_ITEM_EDIT_LABEL_OPTION  1583
#define IDC_BMK_ITEM_EDIT_LABEL_PARAM   1584
#define IDC_BMK_ITEM_EDIT_LABEL_STARTUP 1585
#define IDC_BMK_ITEM_EDIT_LABEL_SHOW    1586
#define IDC_BMK_ITEM_EDIT_LABEL_HOTKEY  1587
#define IDC_CREATE_SHORTCUT_LABEL_NAME  1588
#define IDC_CREATE_SHORTCUT_NAME        1589
#define IDC_CREATE_SHORTCUT_LABEL_TARGET 1590
#define IDC_CREATE_SHORTCUT_TARGET_BROWSE 1591
#define IDC_CREATE_SHORTCUT_GROUP_ADVANCED 1592
#define IDC_CREATE_SHORTCUT_LABEL_STARTUP 1593
#define IDC_CREATE_SHORTCUT_LABEL_HOTKEY 1594
#define IDC_CREATE_SHORTCUT_LABEL_SHOWCMD 1595
#define IDC_CREATE_SHORTCUT_LABEL_DESC  1596
#define IDC_CREATE_SHORTCUT_DESC        1597
#define IDC_FILE_LIST_LABEL_PATH        1598
#define IDC_FILE_LIST_PATH              1599
#define IDC_FILE_LIST_GROUP_OPTION      1600
#define IDC_PARAM_EXEC_LABEL_PATH       1601
#define IDC_PARAM_EXEC_LABEL_INPUT      1602
#define IDC_PARAM_EXEC_LABEL_PARAMETER  1603
#define IDC_PIC_CONV_LABEL_FORMAT       1604
#define IDC_PIC_CONV_COLOR_PATH         1605
#define IDC_RENAME_TIP_LABEL_NUMBER_DIGIT 1606
#define IDC_RENAME_TIP_LABEL_NUMBER_DIGIT_ZERO 1607
#define IDC_RENAME_TIP_LABEL_ORG_FILENAME 1608
#define IDC_RENAME_TIP_LABEL_FULL_FILENAME 1609
#define IDC_RENAME_TIP_LABEL_ONLY_FILENAME 1610
#define IDC_RENAME_TIP_LABEL_EXT        1611
#define IDC_RENAME_TIP_LABEL_TODAY_DATE 1612
#define IDC_RENAME_TIP_LABEL_YEAR       1613
#define IDC_RENAME_TIP_LABEL_MONTH      1614
#define IDC_RENAME_TIP_LABEL_DAY        1615
#define IDC_RENAME_TIP_LABEL_TIME       1616
#define IDC_RENAME_TIP_LABEL_HOUR       1617
#define IDC_RENAME_TIP_LABEL_MINUTE     1618
#define IDC_RENAME_TIP_LABEL_SECOND     1619
#define IDC_RENAME_TIP_LABEL_CREATED_DATE 1620
#define IDC_RENAME_TIP_LABEL_CREATED_YEAR 1621
#define IDC_RENAME_TIP_LABEL_CREATED_MONTH 1622
#define IDC_RENAME_TIP_LABEL_CREATED_DAY 1623
#define IDC_RENAME_TIP_LABEL_CREATED_TIME 1624
#define IDC_RENAME_TIP_LABEL_CREATED_AM_PM 1625
#define IDC_RENAME_TIP_LABEL_CREATED_12HOUR 1626
#define IDC_RENAME_TIP_LABEL_CREATED_24HOUR 1627
#define IDC_RENAME_TIP_LABEL_CREATED_MINUTE 1628
#define IDC_RENAME_TIP_LABEL_CREATED_SECOND 1629
#define IDC_RENAME_TIP_LABEL_MODIFIED_DATE 1630
#define IDC_RENAME_TIP_LABEL_MODIFIED_YEAR 1631
#define IDC_RENAME_TIP_LABEL_MODIFIED_MONTH 1632
#define IDC_RENAME_TIP_LABEL_MODIFIED_DAY 1633
#define IDC_RENAME_TIP_LABEL_MODIFIED_TIME 1634
#define IDC_RENAME_TIP_LABEL_MODIFIED_AM_PM 1635
#define IDC_RENAME_TIP_LABEL_MODIFIED_12HOUR 1636
#define IDC_RENAME_TIP_LABEL_MODIFIED_24HOUR 1637
#define IDC_RENAME_TIP_LABEL_MODIFIED_MINUTE 1638
#define IDC_RENAME_TIP_LABEL_MODIFIED_SECOND 1639
#define IDC_RENAME_EDIT_LABEL_OLD_NAME  1640
#define IDC_BATCH_RENAME_LABEL_PATH     1641
#define IDC_BATCH_RENAME_LABEL_BATCH_FORMAT 1642
#define IDC_BATCH_RENAME_LABEL_FORMAT   1643
#define IDC_BATCH_RENAME_FORMAT_LABEL_NUMBER 1644
#define IDC_BATCH_RENAME_FORMAT_LABEL_LENGTH 1645
#define IDC_BATCH_RENAME_FORMAT_LABEL_INCREASE 1646
#define IDC_BATCH_RENAME_REPLACE_LABEL_OLD 1647
#define IDC_BATCH_RENAME_REPLACE_LABEL_NEW 1648
#define IDC_BATCH_RENAME_REPLACE_LABEL_REPEAT 1649
#define IDC_BATCH_RENAME_INSERT_LABEL_TYPE 1650
#define IDC_BATCH_RENAME_INSERT_LABEL_STRING 1651
#define IDC_BATCH_RENAME_INSERT_LABEL_POS 1652
#define IDC_BATCH_RENAME_DELETE_LABEL_TYPE 1653
#define IDC_BATCH_RENAME_DELETE_LABEL_POS 1654
#define IDC_BATCH_RENAME_DELETE_LABEL_LENGTH 1655
#define IDC_BATCH_RENAME_CASE_LABEL_TYPE 1656
#define IDC_BATCH_RENAME_CASE_LABEL_CASE 1657
#define IDC_BATCH_RENAME_LABEL_SKIP_SPEC_CHAR 1658
#define IDC_BATCH_RENAME_CASE_LABEL_SKIP_SPEC_CHAR 1658
#define IDC_SEARCH_LOC_LABEL_ITEM_LIST  1659
#define IDC_SEARCH_LOC_LINE             1660
#define IDC_SEARCH_LOC_EDIT_PATH        1661
#define IDC_SEARCH_LOC_EDIT_LABEL_PATH  1662
#define IDC_SEARCH_LOC_EDIT_PATH_BROWSE 1663
#define IDC_SEARCH_LOC_EDIT_SUBFOLDER   1664
#define IDC_SEARCH_NAME                 1665
#define IDC_SEARCH_LABEL_NAME           1666
#define IDC_SEARCH_LABEL_TEXT           1667
#define IDC_SEARCH_LABEL_LOC            1668
#define IDC_SEARCH_LABEL_OPTION         1669
#define IDC_SEARCH_GROUP_OPTION         1669
#define IDC_SEARCH_LABEL_TYPE           1670
#define IDC_SEARCH_LABEL_RESULT         1671
#define IDC_SEARCH_STATUS               1672
#define IDC_SEARCH_LABEL_TIME           1673
#define IDC_SEARCH_STOP                 1674
#define IDC_SEL_FILTER_DESC             1675
#define IDC_SEL_FILTER                  1676
#define IDC_SEL_FILTER_STATUS           1677
#define IDC_SEL_FILTER_SEL_ONLY         1678
#define IDC_SEL_FOLDER_DESC             1679
#define IDC_SHARED_PROC_LABEL_PATH      1680
#define IDC_SHARED_PROC_LABEL_LIST      1681
#define IDC_WAIT_DESC                   1682
#define IDC_TEXT_MERGE_LABEL_ENCODING   1683
#define IDC_TEXT_MERGE_LABEL_LIST       1684
#define IDC_FOLDER_SYNC_PATH1           1685
#define IDC_FOLDER_SYNC_PATH2           1686
#define IDC_FOLDER_SYNC_SCAN_OPTION     1687
#define IDC_FOLDER_SYNC_COMPARE_OPTION  1688
#define IDC_FOLDER_SYNC_STATUS          1689
#define IDC_FOLDER_SYNC_LIST            1690
#define IDC_FOLDER_SYNC_LABEL_SCAN_INCLUDE_FILTER 1691
#define IDC_FOLDER_SYNC_LABEL_SCAN_EXCLUDE_FILTER 1692
#define IDC_FOLDER_SYNC_OPTION_LABEL_DIRECTION 1693
#define IDC_SIZE_FORMAT_LABEL_LIST      1694
#define IDC_SIZE_FORMAT_LIST            1695
#define IDC_SIZE_FORMAT_DELETE          1696
#define IDC_SIZE_FORMAT_CONDITION       1697
#define IDC_SIZE_FORMAT_LABEL_MORE      1698
#define IDC_SIZE_FORMAT_SIZE_DISP       1699
#define IDC_SIZE_FORMAT_LABEL_DECIMAL_DIGIT 1700
#define IDC_SIZE_FORMAT_LABEL_DECIMAL_DIGITS 1700
#define IDC_SIZE_FORMAT_LABEL_UNIT      1701
#define IDC_SIZE_FORMAT_LABEL_UNIT1     1701
#define IDC_CFG_TREE                    1702
#define IDC_CFG_ADV_HOTKEY_LABEL_CF     1703
#define IDC_CFG_ADV_HOTKEY_LABEL_WINDOW_KEY 1704
#define IDC_CFG_ADV_HOTKEY_LABEL_HOTKEY 1705
#define IDC_CFG_ADV_PATH_LIST           1706
#define IDC_CFG_CONTENTS_GROUP_OPTION   1711
#define IDC_CFG_CONTENTS_GROUP_BOOKMARK 1712
#define IDC_CFG_CONTENTS_LABEL_BOOKMARK_COLOR 1713
#define IDC_CFG_DISP_LABEL_ACTIVE_VIEW_COLOR 1714
#define IDC_CFG_DISP_GROUP_PATHBAR      1715
#define IDC_CFG_DISP_SIZE_LABEL_SINGLE_ITEM_UNIT 1716
#define IDC_CFG_DISP_SIZE_LABEL_MULTIPLE_ITEMS_UNIT 1717
#define IDC_CFG_EXP_DISP_LABEL_SHOW_LIST_TYPE 1718
#define IDC_CFG_EXP_DISP_LABEL_TEXT_NAME_CASE 1719
#define IDC_CFG_EXP_DISP_LABEL_SIZE_UNIT 1720
#define IDC_CFG_EXP_FILTER_LABEL_LIST   1721
#define IDC_CFG_EXP_THUMB_LABEL_WIDTH   1722
#define IDC_CFG_EXP_THUMB_LABEL_HEIGHT  1723
#define IDC_CFG_EXP_THUMB_LIMIT_SIZE    1724
#define IDC_CFG_EXP_THUMB_LABEL_PRIORITY 1725
#define IDC_CFG_EXP_THUMB_LABEL_CAUTION 1726
#define IDC_CFG_EXP_THUMB_LABEL_SUPPORTED_IMAGE 1727
#define IDC_CFG_GENERAL_GROUP_MOUSE_CLICK 1728
#define IDC_CFG_GENERAL_GROUP_GENERAL   1729
#define IDC_CFG_GENERAL_LABEL_EXTENSION 1730
#define IDC_CFG_STYLE_LABEL_MAIN_TOOLS  1731
#define IDC_CFG_STYLE_LABEL_FOLDER_PANE 1732
#define IDC_CFG_STYLE_LABEL_EXPLORER_WINDOW 1733
#define IDC_CFG_EXP_VIEW_GROUP_VIEW_SET 1734
#define IDC_CFG_EXP_VIEW_LABEL_DEFAULT_VIEW_STYLE 1735
#define IDC_CFG_EXP_VIEW_LABEL_DEFAULT_SORT 1736
#define IDC_CFG_EXP_VIEW_LABEL_DEFAULT_SORT_ORDER 1737
#define IDC_CFG_EXP_WND_LABEL_TEXT_COLOR_DESC 1738
#define IDC_CFG_EXP_WND_LABEL_BKGND_COLOR_DESC 1739
#define IDC_CFG_FLD_WND_GROUP_CUSTOM    1740
#define IDC_CFG_FUNC_LABEL_NAME_COPY_SEPARATOR 1741
#define IDC_CFG_FUNC_DRAG_GROUP_DRAG_START 1742
#define IDC_CFG_FUNC_DRAG_GROUP_DRAGGING 1743
#define IDC_CFG_FUNC_DRAG_LABEL_FOLDER_EXPAND_TIME 1744
#define IDC_CFG_FUNC_DRAG_LABEL_SCROLL_TIME 1745
#define IDC_CFG_FUNC_DRAG_GROUP_DROP    1746
#define IDC_CFG_FUNC_DRAG_GROUP_ETC     1747
#define IDC_CFG_FUNC_DRAG_LABEL_DEFAULT_OPERATION 1748
#define IDC_CFG_FUNC_FILE_ASS_LABEL_LIST 1749
#define IDC_CFG_FUNC_FILE_OP_GROUP_EXTERNAL_PROGRAM 1750
#define IDC_CFG_FUNC_RENAME_GROUP_COMMAND 1751
#define IDC_CFG_FUNC_RENAME_GROUP_SINGLE_RENAME 1752
#define IDC_CFG_FUNC_RENAME_GROUP_EXT   1753
#define IDC_FILTER_SET_LABEL_NAME       1754
#define IDC_FILTER_SET_LABEL_EXTS       1755
#define IDC_FILTER_SET_LABEL_COLOR      1756
#define IDC_FILTER_SET_LABEL_COLOR_CODE 1757
#define IDC_FILTER_SET_LABEL_ICON       1758
#define IDC_FILE_ASS_SET_LABEL_NAME     1759
#define IDC_FILE_ASS_SET_NAME           1760
#define IDC_FILE_ASS_SET_GROUP_METHOD   1761
#define IDC_FILE_ASS_SET_GROUP_TYPE     1762
#define IDC_FILE_ASS_SET_LABEL_FILTER   1763
#define IDC_FILE_ASS_SET_LABEL_EXTS     1764
#define IDC_FILE_ASS_SET_LABEL_PROGRAM  1765
#define IDC_CUSTOM_TOOLBAR_LABEL_TEXT_OPTION 1766
#define IDC_CUSTOM_TOOLBAR_LABEL_ICON_OPTION 1767
#define IDC_FILE_SCRAP_LIST             1768
#define IDC_FILE_SCRAP_STATUS           1769
#define IDC_HISTORY_TAB                 1770
#define IDC_CUSTOM1                     1770
#define IDC_SEARCH_STATUS_BAR           1770
#define IDC_HISTORY_TREE                1771
#define IDC_HISTORY_STATUS              1772
#define IDC_DRIVE_INFO_TREE             1773
#define ID_FILE_NEW_FOLDER              30000
#define ID_FILE_NEW_FILE                30001
#define ID_FILE_NEW_TEXT                30002
#define ID_FILE_NEW_LINK                30003
#define ID_FILE_NEW_ITEMS               30004
#define ID_FILE_NEW_DYNAMIC_MENU        30010
#define ID_FILE_NEW_FIRST               30011
#define ID_FILE_NEW_LAST                30110
#define ID_FILE_LINK                    30111
#define ID_FILE_DELETE                  30112
#define ID_FILE_RENAME                  30113
#define ID_FILE_IMAGE_CONV              30114
#define ID_FILE_PROPERTY                30115
#define ID_FILE_CRC_CREATE              30116
#define ID_FILE_CRC_VERIFY              30117
#define ID_FILE_TEXT_MERGE              30118
#define ID_FILE_LIST_FILE               30119
#define ID_TRAY_APP_EXIT                30120
#define ID_FILE_DUPLICATE               30121
#define ID_FILE_ATTRTIME                30122
#define ID_APP_MINIMIZE_TRAY            30133
#define ID_FILE_EXEC_PARAM              30134
#define ID_FILE_EXEC                    30135
#define ID_FILE_VIEW                    30136
#define ID_FILE_EDIT                    30137
#define ID_FILE_VIEWER_ASS              30138
#define ID_FILE_EDITOR_ASS              30139
#define ID_FILE_SHELL_ASS               30140
#define ID_FILE_SPLIT                   30141
#define ID_FILE_COMBINE                 30142
#define ID_FILE_MERGE                   30143
#define ID_FILE_ENCODE                  30144
#define ID_FILE_DECODE                  30145
#define ID_FILE_BATCH_RENAME_ALL        30146
#define ID_FILE_BATCH_RENAME_FILE       30147
#define ID_FILE_BATCH_RENAME_FOLDER     30148
#define ID_FILE_RECENT_DYNAMIC_MENU     30200
#define ID_FILE_RECENT_FIRST            30201
#define ID_FILE_RECENT_LAST             30300
#define ID_EDIT_NAME_COPY               31000
#define ID_EDIT_FILE_SCRAP_ADD          31000
#define ID_EDIT_FILENAME_COPY           31001
#define ID_EDIT_PATH_COPY               31002
#define ID_EDIT_DEV_PATH_COPY           31003
#define ID_EDIT_PASTE_COPY              31005
#define ID_EDIT_FOLDER_MOVE             31006
#define ID_EDIT_FOLDER_COPY             31007
#define ID_EDIT_UNSEL_NAME              31007
#define ID_EDIT_SEL_ALL                 31008
#define ID_EDIT_SEL_REVERSAL            31009
#define ID_EDIT_SEL_NAME                31010
#define ID_EDIT_SEL_SAME_EXT            31011
#define ID_EDIT_SEL_SAME_FILTER         31012
#define ID_EDIT_SEL_FILTER              31013
#define ID_EDIT_SEL_FOLDER              31014
#define ID_EDIT_SEL_FILE                31015
#define ID_EDIT_UNSEL_ALL               31016
#define ID_EDIT_UNSEL_FILE              31018
#define ID_EDIT_UNSEL_FILTER            31019
#define ID_EDIT_UNSEL_FOLDER            31020
#define ID_EDIT_SEARCH_LOCATION         31021
#define ID_EDIT_URL_COPY                31024
#define ID_EDIT_FILE_SCRAP_CUR_COPY     31101
#define ID_EDIT_FILE_SCRAP_CUR_MOVE     31102
#define ID_EDIT_FILE_SCRAP_DELETE       31103
#define ID_EDIT_FILE_SCRAP_CLIPBOARD_CUT 31104
#define ID_EDIT_FILE_SCRAP_CLIPBOARD_COPY 31105
#define ID_EDIT_FILE_SCRAP_VIEW         31106
#define ID_EDIT_FILE_SCRAP_LIST_REMOVE  31107
#define ID_EDIT_FILE_SCRAP_DROP         31108
#define ID_EDIT_FILE_SCRAP_GROUP_ADD    31109
#define ID_EDIT_FILE_SCRAP_GROUP_VIEW   31110
#define ID_EDIT_FILE_SCRAP_GROUP_DEFAULT 31111
#define ID_GO_DRIVE                     32000
#define ID_GO_BOOKMARK                  32001
#define ID_GO_BOOKMARK_ADD              32002
#define ID_GO_BOOKMARK_MODIFY           32003
#define ID_GO_UP                        32004
#define ID_GO_ROOT                      32005
#define ID_GO_BACK                      32006
#define ID_GO_FORWARD                   32007
#define ID_GO_HISTORY                   32008
#define ID_GO_UP_BOX                    32009
#define ID_GO_BACK_BOX                  32010
#define ID_GO_BACK_CLEAR                32011
#define ID_GO_FORWARD_BOX               32012
#define ID_GO_FORWARD_CLEAR             32013
#define ID_GO_HISTORY_CLEAR             32014
#define ID_GO_HISTORY_BOX               32015
#define ID_GO_HISTORY_ALL_CLEAR         32016
#define ID_GO_SIBLING_UP                32017
#define ID_GO_SIBLING_DOWN              32018
#define ID_GO_PATH                      32019
#define ID_GO_DRIVE_DETAIL              32020
#define ID_GO_FLYEXPLORER               32021
#define ID_GO_INIT_FOLDER_ALL           32022
#define ID_GO_INIT_FOLDER_1             32023
#define ID_GO_INIT_FOLDER_2             32024
#define ID_GO_INIT_FOLDER_3             32025
#define ID_GO_INIT_FOLDER_4             32026
#define ID_GO_INIT_FOLDER_5             32027
#define ID_GO_INIT_FOLDER_6             32028
#define ID_GO_WORKING_FOLDER            32029
#define ID_GO_WORKING_FOLDER_RESET_ALL  32030
#define ID_GO_SYSTEM_DESKTOP            32100
#define ID_GO_SYSTEM_LIBRARIES          32101
#define ID_GO_SYSTEM_DOCUMENTS          32102
#define ID_GO_SYSTEM_PICTURES           32103
#define ID_GO_SYSTEM_MUSIC              32104
#define ID_GO_SYSTEM_VIDEOS             32105
#define ID_GO_SYSTEM_MYDOCUMENT         32106
#define ID_GO_SYSTEM_MYCOMPUTER         32107
#define ID_GO_SYSTEM_NETWORK            32108
#define ID_GO_SYSTEM_CONTROLS           32109
#define ID_GO_SYSTEM_STARTUP            32110
#define ID_GO_SYSTEM_TEMPORARY          32111
#define ID_GO_SYSTEM_RECYCLE            32112
#define ID_GO_SYSTEM_PROGRAMFILES       32113
#define ID_GO_SYSTEM_WINDOWS            32114
#define ID_GO_SYSTEM_WINDOWS_SYSTEM     32115
#define ID_GO_SYSTEM_RECENT             32116
#define ID_GO_SYSTEM_SENDTO             32117
#define ID_GO_SYSTEM_COMMON             32118
#define ID_GO_SYSTEM_INTERNETCACHE      32119
#define ID_GO_SYSTEM_FONTS              32120
#define ID_GO_SYSTEM_FAVORITES          32121
#define ID_GO_SYSTEM_INTERNETCOOKIE     32122
#define ID_GO_SYSTEM_HISTORY            32123
#define ID_GO_SYSTEM_APPDATA            32124
#define ID_VIEW_DRIVEBAR                33000
#define ID_VIEW_BOOKMARKBAR             33001
#define ID_VIEW_ADDRESSBAR              33002
#define ID_VIEW_PATHBAR                 33003
#define ID_VIEW_ACTIVATEWND             33004
#define ID_VIEW_DRIVEBAR_SHORTTEXT      33005
#define ID_VIEW_DRIVEBAR_LONGTEXT       33006
#define ID_VIEW_DRIVEBAR_REFRESH        33007
#define ID_VIEW_DRIVEBAR_LEFT           33008
#define ID_VIEW_DRIVEBAR_RIGHT          33009
#define ID_VIEW_DRIVEBAR_VIEWSPLIT      33010
#define ID_VIEW_DRIVEBAR_WRAPABLE       33011
#define ID_VIEW_BOOKMARKBAR_WRAPABLE    33012
#define ID_VIEW_BOOKMARKBAR_REFRESH     33013
#define ID_VIEW_BOOKMARKBAR_NONAME      33014
#define ID_VIEW_BOOKMARKBAR_NAME        33015
#define ID_VIEW_ADDRESSBAR_SHOW         33016
#define ID_VIEW_TOOL_LOCK               33017
#define ID_VIEW_TOOLBAR_CUSTOMIZE       33018
#define ID_VIEW_FOLDER_TREE_NONE        33019
#define ID_VIEW_FOLDER_TREE_SHOW        33020
#define ID_VIEW_FOLDER_TREE_SINGLE_PANE 33021
#define ID_VIEW_FOLDER_TREE_EACH_PANE   33022
#define ID_VIEW_FOLDER_TREE_LEFT_PANE   33023
#define ID_VIEW_FOLDER_TREE_RIGHT_PANE  33024
#define ID_VIEW_BAR_SEARCH              33025
#define ID_VIEW_REFRESH                 33040
#define ID_VIEW_STOP                    33041
#define ID_VIEW_SHOW_MAINFRAME          33042
#define ID_VIEW_PICVIEWER               33043
#define ID_VIEW_ARRAY_ASCENDING         33044
#define ID_VIEW_ARRAY_DECENDING         33045
#define ID_VIEW_STYLE                   33100
#define ID_VIEW_STYLE_EXTRALARGEICONS   33101
#define ID_VIEW_STYLE_MEDIUMICONS       33102
#define ID_VIEW_STYLE_LARGEICONS        33103
#define ID_VIEW_STYLE_SMALLICONS        33104
#define ID_VIEW_STYLE_LIST              33105
#define ID_VIEW_STYLE_DETAILS           33106
#define ID_VIEW_STYLE_THUMBNAIL         33107
#define ID_VIEW_STYLE_TILES             33108
#define ID_VIEW_STYLE_CONTENTS          33108
#define ID_VIEW_COLUMN_SET              33120
#define ID_VIEW_COLUMN_NAME             33121
#define ID_VIEW_COLUMN_SIZE             33122
#define ID_VIEW_COLUMN_TYPE             33123
#define ID_VIEW_COLUMN_DATE             33124
#define ID_VIEW_COLUMN_ATTR             33125
#define ID_VIEW_COLUMN_EXT              33126
#define ID_VIEW_ARRAY_NAME              33220
#define ID_VIEW_ARRAY_TYPE              33221
#define ID_VIEW_ARRAY_SIZE              33222
#define ID_VIEW_ARRAY_DATE              33223
#define ID_VIEW_ARRAY_ATTR              33224
#define ID_VIEW_ARRAY_EXT               33225
#define ID_VIEW_PIC_BEGIN               33900
#define ID_VIEW_PIC_DOCKING             33900
#define ID_VIEW_PIC_RATIO               33901
#define ID_VIEW_PIC_CLIENT              33902
#define ID_VIEW_PIC_ZOOM_IN             33903
#define ID_VIEW_PIC_ZOOM_OUT            33904
#define ID_VIEW_PIC_ZOOM_100            33905
#define ID_VIEW_PIC_CLOSE               33906
#define ID_VIEW_PIC_LOCK                33907
#define ID_VIEW_PIC_LOCK_100            33908
#define ID_VIEW_PIC_BACK_CENTER         33909
#define ID_VIEW_PIC_BACK_TILE           33910
#define ID_VIEW_PIC_BACK_STRETCH        33911
#define ID_VIEW_PIC_AUTO_HIDE           33912
#define ID_VIEW_PIC_SHOW_FILENAME       33913
#define ID_VIEW_PIC_HIDE                33914
#define ID_VIEW_PIC_SHOW_HIDE           33915
#define ID_VIEW_PIC_LOCK_THUMBNAIL      33916
#define ID_VIEW_PIC_END                 33999
#define ID_TOOL_EMPTY_RECYCLEBIN        34000
#define ID_TOOL_CMD                     34001
#define ID_TOOL_DOS_CMD                 34002
#define ID_TOOL_NETWORK_CONNECT         34004
#define ID_TOOL_NETWORK_DISCONNECT      34005
#define ID_TOOL_ACCELERATOR             34007
#define ID_TOOL_OPTION                  34008
#define ID_TOOL_WINDOWS_EXPLORER        34009
#define ID_TOOL_SHARED_PROC             34011
#define ID_TOOL_FOLDER_SYNC             34012
#define ID_TOOL_SAVE_OPTION             34013
#define ID_WINDOW_NEXT                  35000
#define ID_WINDOW_PREV                  35001
#define ID_WINDOW_SPLIT_SINGLE          35002
#define ID_WINDOW_SPLIT_1x2             35003
#define ID_WINDOW_SPLIT_2x1             35004
#define ID_WINDOW_SPLIT_2x2             35005
#define ID_WINDOW_SPLIT_1x3             35006
#define ID_WINDOW_SPLIT_2x3             35007
#define ID_WINDOW_SPLIT_EQUALLY         35010
#define ID_WINDOW_LIST                  35011
#define ID_WINDOW_TAB_NEW               35012
#define ID_WINDOW_TAB_DUPLICATE         35013
#define ID_WINDOW_TAB_DUPLICATE_ON_CURSOR 35014
#define ID_WINDOW_TAB_CLOSE             35015
#define ID_WINDOW_TAB_CLOSE_ON_CURSOR   35016
#define ID_WINDOW_TAB_CLOSE_ALL_BUT_THIS 35017
#define ID_WINDOW_TAB_CLOSE_ALL_BUT_THIS_ON_CURSOR 35018
#define ID_WINDOW_TAB_CLOSE_ALL         35019
#define ID_WINDOW_TAB_FIRST             35020
#define ID_WINDOW_TAB_PREVIOUS          35021
#define ID_WINDOW_TAB_NEXT              35022
#define ID_WINDOW_TAB_LAST              35023
#define ID_WINDOW_SPLIT_SWAP            35031
#define ID_WINDOW_COPY                  35032
#define ID_WINDOW_MOVE                  35033
#define ID_WINDOW_1_COPY                35034
#define ID_WINDOW_1_MOVE                35035
#define ID_WINDOW_2_COPY                35036
#define ID_WINDOW_2_MOVE                35037
#define ID_WINDOW_SPLIT_EQUAL           35038
#define ID_WINDOW_COMPARE               35039
#define ID_WINDOW_DUAL_MOVE             35040
#define ID_WINDOW_DUAL_COPY             35041
#define ID_WINDOW_DUAL_DELETE           35042
#define ID_WINDOW_SPLIT_10              35043
#define ID_WINDOW_SPLIT_20              35044
#define ID_WINDOW_SPLIT_30              35045
#define ID_WINDOW_SPLIT_40              35046
#define ID_WINDOW_SPLIT_50              35047
#define ID_WINDOW_SPLIT_60              35048
#define ID_WINDOW_SPLIT_70              35049
#define ID_WINDOW_SPLIT_80              35050
#define ID_WINDOW_SPLIT_90              35051
#define ID_WINDOW_FILE_COMPARE          35052
#define ID_WINDOW_SPLIT_OTHER_EQUAL     35053
#define ID_APP_HELP                     36500
#define ID_APP_HELP_FIND                36501
#define ID_APP_ACCELERATOR              36502
#define ID_APP_TIP                      36503
#define ID_APP_HOMEPAGE                 36504
#define ID_APP_EMAIL                    36505
#define ID_DRIVE_DYNAMIC_MENU           43000
#define ID_DRIVE_FIRST                  43001
#define ID_DRIVE_LAST                   43026
#define ID_BOOKMARK_DYNAMIC_MENU        43100
#define ID_BOOKMARK_FIRST               43101
#define ID_BOOKMARK_LAST                43199
#define ID_GO_UP_DYNAMIC_MENU           43200
#define ID_GO_UP_FIRST                  43201
#define ID_GO_UP_LAST                   43299
#define ID_GO_BACKWARD_DYNAMIC_MENU     43300
#define ID_GO_BACKWARD_FIRST            43301
#define ID_GO_BACKWARD_LAST             43399
#define ID_GO_FORWARD_DYNAMIC_MENU      43400
#define ID_GO_FORWARD_FIRST             43401
#define ID_GO_FORWARD_LAST              43499
#define ID_GO_HISTORY_DYNAMIC_MENU      43500
#define ID_GO_HISTORY_FIRST             43501
#define ID_GO_HISTORY_LAST              43599
#define ID_GO_WORKING_FOLDER_DYNAMIC_MENU 43600
#define ID_GO_WORKING_FOLDER_FIRST      43601
#define ID_GO_WORKING_FOLDER_0          43601
#define ID_GO_WORKING_FOLDER_1          43602
#define ID_GO_WORKING_FOLDER_2          43603
#define ID_GO_WORKING_FOLDER_3          43604
#define ID_GO_WORKING_FOLDER_4          43605
#define ID_GO_WORKING_FOLDER_LAST       43619
#define ID_GO_WORKING_FOLDER_SET_DYNAMIC_MENU 43620
#define ID_GO_WORKING_FOLDER_SET_FIRST  43621
#define ID_GO_WORKING_FOLDER_SET_0      43621
#define ID_GO_WORKING_FOLDER_SET_1      43622
#define ID_GO_WORKING_FOLDER_SET_2      43623
#define ID_GO_WORKING_FOLDER_SET_3      43624
#define ID_GO_WORKING_FOLDER_SET_4      43625
#define ID_GO_WORKING_FOLDER_SET_LAST   43639
#define ID_GO_WORKING_FOLDER_RESET_DYNAMIC_MENU 43640
#define ID_GO_WORKING_FOLDER_RESET_FIRST 43641
#define ID_GO_WORKING_FOLDER_RESET_0    43641
#define ID_GO_WORKING_FOLDER_RESET_1    43642
#define ID_GO_WORKING_FOLDER_RESET_2    43643
#define ID_GO_WORKING_FOLDER_RESET_3    43644
#define ID_GO_WORKING_FOLDER_RESET_4    43645
#define ID_GO_WORKING_FOLDER_RESET_LAST 43659
#define ID_SR_ADD_FILE_SCRAP            45000
#define ID_SR_REMOVE_LIST               45001
#define ID_SR_CLOSE                     45002
#define ID_SR_VIEW_ICON                 45003
#define ID_SR_VIEW_SMALLICON            45004
#define ID_SR_VIEW_LIST                 45005
#define ID_SR_VIEW_DETAIL               45006
#define ID_FCD_CLOSE                    45400
#define ID_FCD_COPY                     45401
#define ID_FCD_MOVE                     45402
#define ID_FCD_DELETE                   45403
#define ID_FCD_VIEW                     45404
#define ID_FCD_REMOVE                   45405
#define ID_FCD_ALWAYS_TOP_MOST          45406
#define ID_FCD_TRANSPARENT              45407
#define ID_FCD_CLIPBOARD_COPY           45408
#define ID_FCD_CLIPBOARD_CUT            45409
#define ID_FCD_GROUP_CUR_ADD            45410
#define ID_FCD_GROUP_VIEW               45411
#define ID_FCD_TRANSPARENT_20           45412
#define ID_FCD_TRANSPARENT_40           45413
#define ID_FCD_TRANSPARENT_60           45414
#define ID_FCD_TRANSPARENT_80           45415
#define ID_FCD_TRANSPARENT_0            45416
#define ID_FCD_GROUP                    45417
#define ID_FCD_GROUP_DEFAULT            45418
#define ID_SRN_FORMAT_MENU_NUMBER       45500
#define ID_SRN_FORMAT_MENU_FULLNAME     45501
#define ID_SRN_FORMAT_MENU_FILENAME     45502
#define ID_SRN_FORMAT_MENU_EXTENSION    45503
#define ID_SRN_FORMAT_MENU_DATE         45504
#define ID_SRN_FORMAT_MENU_NUMBER_ZERO  45505
#define ID_SRN_FORMAT_MENU_YEAR         45506
#define ID_SRN_FORMAT_MENU_MONTH        45507
#define ID_SRN_FORMAT_MENU_DAY          45508
#define ID_SRN_FORMAT_MENU_TIME         45509
#define ID_SRN_FORMAT_MENU_HOUR         45510
#define ID_SRN_FORMAT_MENU_MINUTE       45511
#define ID_SRN_FORMAT_MENU_SECOND       45512
#define ID_SRN_FORMAT_MENU_CREATION_DATE 45513
#define ID_SRN_FORMAT_MENU_CREATION_YEAR 45514
#define ID_SRN_FORMAT_MENU_CREATION_MONTH 45515
#define ID_SRN_FORMAT_MENU_CREATION_DAY 45516
#define ID_SRN_FORMAT_MENU_CREATION_TIME 45517
#define ID_SRN_FORMAT_MENU_CREATION_HOUR 45518
#define ID_SRN_FORMAT_MENU_CREATION_MINUTE 45519
#define ID_SRN_FORMAT_MENU_CREATION_SECOND 45520
#define ID_SRN_FORMAT_MENU_CREATION_AM_PM_HOUR 45521
#define ID_SRN_FORMAT_MENU_CREATION_24_HOUR 45522
#define ID_SRN_FORMAT_MENU_CREATION_12_HOUR 45523
#define ID_SRN_FORMAT_MENU_LAST_WRITE_DATE 45524
#define ID_SRN_FORMAT_MENU_LAST_WRITE_YEAR 45525
#define ID_SRN_FORMAT_MENU_LAST_WRITE_MONTH 45526
#define ID_SRN_FORMAT_MENU_LAST_WRITE_DAY 45527
#define ID_SRN_FORMAT_MENU_LAST_WRITE_TIME 45528
#define ID_SRN_FORMAT_MENU_LAST_WRITE_AM_PM_HOUR 45529
#define ID_SRN_FORMAT_MENU_LAST_WRITE_12_HOUR 45530
#define ID_SRN_FORMAT_MENU_LAST_WRITE_24_HOUR 45531
#define ID_SRN_FORMAT_MENU_LAST_WRITE_MINUTE 45532
#define ID_SRN_FORMAT_MENU_LAST_WRITE_SECOND 45533
#define ID_SRN_FORMAT_MENU_ORIGINAL_FILENAME_RANGE 45534
#define ID_LOC_NEW                      45600
#define ID_LOC_MODIFY                   45601
#define ID_LOC_DELETE                   45602
#define ID_SCRAP_GROUP_NEW              45700
#define ID_SCRAP_GROUP_MODIFY           45701
#define ID_SCRAP_GROUP_DELETE           45702
#define ID_SCRAP_GROUP_DEFAULT          45703
#define ID_SYNC_LEFT                    45800
#define ID_SYNC_RIGHT                   45801
#define ID_SYNC_NOT                     45802
#define ID_SYNC_NONE                    45803
#define ID_SYNC_ORIGINAL                45804
#define ID_NEW_FORMAT_MENU_NUMBER       45900
#define ID_NEW_FORMAT_MENU_NUMBER_ZERO  45901
#define ID_NEW_FORMAT_MENU_DATE         45902
#define ID_NEW_FORMAT_MENU_YEAR         45903
#define ID_NEW_FORMAT_MENU_MONTH        45904
#define ID_NEW_FORMAT_MENU_DAY          45905
#define ID_NEW_FORMAT_MENU_TIME         45906
#define ID_NEW_FORMAT_MENU_HOUR         45907
#define ID_NEW_FORMAT_MENU_MINUTE       45908
#define ID_NEW_FORMAT_MENU_SECOND       45909
#define IDS_TRAY_NOTIFY                 61484

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        424
#define _APS_NEXT_COMMAND_VALUE         50000
#define _APS_NEXT_CONTROL_VALUE         1771
#define _APS_NEXT_SYMED_VALUE           126
#endif
#endif
